### ISSUE TITLE
[Typo]: Solar Flux Quests

### ISSUE THREAD

**Issue by Blackalf14** [MLDEG/Ragnamod_VII#10]
### Modpack version

7.1.0

### Where is the typo located?

In every Solar Flux Quests descriptions the Solar Panels are described as the first Tier
![Capture d'écran 2024-01-21 150530](https://github.com/MLDEG/Ragnamod_VII/assets/157293895/c26a1fd6-2031-4d12-b9c5-2c2bdefab65d)

### Fix

Change "Solar Panel I" for each quest into their respective tier

**Comment by MLDEG** [comment]
Ah oups, thanks, it will be fixed in the next update :)
