### ISSUE TITLE
[Bug]: Chaotic chicken crashes the server/game

### ISSUE THREAD

**Issue by Xplodin** [MLDEG/Ragnamod_VII#101]
### Modpack version

7.1.3

### Description

thats about it.

### Crashlogs

https://gist.github.com/Xplodin/49b0d8a7166786546b338f33392323ee

### Steps to reproduce

craft chaotic chicken
crash

### Expected behavior

craft chaotic chicken
not crash the server after attempts on rejoining 

### Anything else to note?

I really dont think there is much else to note

**Comment by MLDEG** [comment]
Try uninstalling the pack and reinstalling it because I crafted the chaotic chicken weeks ago on my let's play on Server and I had no problem, so I am unable to reproduce your problem.
