### ISSUE TITLE
[Bug]: Crash à répétition : Evilcraft

### ISSUE THREAD

**Issue by ArthurMTX** [MLDEG/Ragnamod_VII#102]
### Modpack version

7.1.3

### Description

Crashlog d'un crash récurent sur un serveur lors de la sortie d'une zone avec des blocks spécifiques (possiblement dû à Evilcraft). Ce crash n'était pas là avant la version 7.1.3.

### Crashlogs

https://pste.ch/ayiramerat.pl

### Steps to reproduce

3 blood infuser avec miel vers condensed blood 
1 blood infuser de dark gem
1 blood infuser avec blood-waxed coal
1 blood infuser avec blood-potash
2 blood infuser vide
Tous fill avec Tenacity 3 et 12 Velocity
Alimentés en blood avec des Condensed blood
les 8 blood infusers sont connectés à des Entanglanted blocks pour être remplis.

Après 10-15 minutes dans la zone, si on se déplace loin via tp d'une sharestone (1000 block+) --> une chance de crash, quelque soit le joueur, quelque soit la destination 
Bug récurrent (plusieurs fois par heure, toujours la même erreur), aucun bug si le joueur ne sort pas de la zone 

### Expected behavior

Pouvoir sortir de la zone sans crash.

### Anything else to note?

J'ai rédigé cette issue pour SolyTerre_ (qui n'a pas GitHub), voici son Discord si besoin de contact : solyterre_

**Comment by MLDEG** [comment]
Impossible de reproduire le crash de mon côté et le crash log donne en plus les github des mods pour faire des reports là-bas :)

https://github.com/CyclopsMC/EvilCraft/issues
https://github.com/CyclopsMC/CyclopsCore/issues
