### ISSUE TITLE
Explication premier donjon Blood Magic

### ISSUE THREAD

**Issue by Blackalf14** [MLDEG/Ragnamod_VII#103]
### Describe the feature

La quête du raw demonite lié au deuxième donjon explique bien au joueur qu'il faut des iron keys afin de d'avancer dans celui-ci mais la quête du Tau / Saturated Tau lié au premier donjon ne l'explique pas ce qui peut porter à confusion, finalement l'explication nous est présenté seulement lorsqu'on a déjà visité le premier donjon et donc appris son fonctionnement.
Ajouter l'explication à la quête du Saturated Tau aiderait à la compréhension des joueurs

### Reasons why this should be added

Ajout d'informations

**Comment by MLDEG** [comment]
Je n'ai absolument rien compris à ton explication, mais il y a bien toutes les infos nécessaires dans la quête pour le saturated tau
