### ISSUE TITLE
[Bug]: Donjon reine Twilite forest serveur crash

### ISSUE THREAD

**Issue by tijo080** [MLDEG/Ragnamod_VII#107]
### Modpack version

1.7.4

### Description

le serveur a crash après avoir rammaser un ou des items du boss

### Crashlogs

[Log crash.zip](https://github.com/MLDEG/Ragnamod_VII/files/14551956/Log.crash.zip)

### Steps to reproduce

faire le bos et drop les items

### Expected behavior

Crash serveur

**Comment by MLDEG** [comment]
Crashlogs
If you have a crash logs, please post it here. please use https://pste.ch/, or https://hastebin.com/
