### ISSUE TITLE
[Bug]: Serveur Crash

### ISSUE THREAD

**Issue by tijo080** [MLDEG/Ragnamod_VII#108]
### Modpack version

1.7.4

### Description

Lorsque que mon amie a fait le boss de la twilight forest (Ice Queen) j'ai du utiliser un backup car quand Elle seule se connectait le serveur crash après avoir looté le coffre de boss

### Crashlogs

https://hastebin.com/share/usaboyeyuk.perl le premier (17h34)
https://hastebin.com/share/uguwofetis.perl  le 2e (17h45)
https://hastebin.com/share/dawodoleja.perl le 3e (17h59)

### Steps to reproduce

Faire le boss Ice Queen et looté son coffre

### Expected behavior

ne pas avoir de crash et permettre au joueur de profité de ses loots

### Anything else to note?

le serveur est sur Ubuntu 22.04.4 server clean install avec aucun addon juste un utilisateur java 17 et le serveur Ragnamod VII

**Comment by MLDEG** [comment]
Le problème vient d'une entité "twilightforest:ice_snowball" il faut le kill sur le server pour régler le problème.
Si celui-ci persiste, il faudra reporter sur le github indiqué dans le crashlog 
Issue tracker URL: https://github.com/TeamTwilight/twilightforest/issues
