### ISSUE TITLE
[Bug]: Lead from Chemlib impossible to get with Lead Ingot

### ISSUE THREAD

**Issue by Bagra67** [MLDEG/Ragnamod_VII#11]
### Modpack version

7.1.0

### Description

Hello,

I check the craft of the lead from ChemLib and I can't use the Lead Ingot to make it
To be sure it's a bug I check to make copper and I can use the Copper Ingot

With more research it look likes all Thermal Series ingot of normal metal can't be turn in ChemLib atom

Is it a feature of the pack ? Or a bug

### Steps to reproduce

1: Check on JEI the Lead from ChemLib craft
2: Scroll through all craft and can't find the ingot craft

### Expected behavior

In my opinion, the ingot, and all their form could be turn into the ChemLib atom form

**Comment by MLDEG** [comment]
Thanks for the report.
It will be fixed in the next update, and also I added more metal crafts in the Dissolver (silver, iridium, nickel, osmium, aluminum, lead, tin, uranium, iron, gold, copper, sulfur/ Block, raw, dusts, plate, rod, etc.)
