### ISSUE TITLE
[Bug]: Modpack is tagging forge:experience onto a non-equivalant fluid.

### ISSUE THREAD

**Issue by Flanks255** [MLDEG/Ragnamod_VII#110]
### Modpack version

7.4

### Description

The Liquid Experience from Create Enchantment Industry is being tagged in the pack with forge:experience.
This liquid is not an equivalent for other mods fluids using the tag.

The established community convention for fluids using the forge:experience tag is 20mb/1xp.
CEI's fluid uses 1mb/1xp, and the author has stated it is not intended to be used in other mods when asked.

[kubejs script adding the tag](https://github.com/MLDEG/Ragnamod_VII/blob/main/kubejs/server_scripts/tags.js#L373)

CEI issue before i realized they weren't tagging it themselves.
https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry/issues/149

MGU issue that started the investigation.
https://github.com/vadis365/Mob-Grinding-Utils/issues/281

**Comment by MLDEG** [comment]
Ok, I see, so I'm just thinking of removing this fluid from the forge:experience tag to avoid problems :)

**Comment by Flanks255** [comment]
![thumbs-up-double-thumbs-up](https://github.com/MLDEG/Ragnamod_VII/assets/32142731/8f7d09f1-2b3d-4a5a-914f-dec1895661ac)
