### ISSUE TITLE
Changer les dépendances liées à la quête du plastique d'Industrial Foregoing

### ISSUE THREAD

**Issue by Blackalf14** [MLDEG/Ragnamod_VII#111]
### Describe the feature

Depuis la 7.0.12 les plastiques de PnC et Industrial Foregoing ont reçu le même tag.
Le plastique d'Industrial Foregoing n'est donc plus obligatoire dans la progression.
Cependant la quête pour celui-ci bloque toujours la suite de la progression des quêtes.
L'idée serait donc de retirer la quête du fluid extractor et du plastique de la progression et de les mettre sur le côté (comme pour les animal rancher, block breaker, ect...).

### Reasons why this should be added

Permet d'informer le joueur sur une nouvelle façon de fabriquer le plastique sans rendre le tout obligatoire

**Comment by MLDEG** [comment]
Je ne changerai pas cette quête, car l'idée de la page est d'expliquer Industrial Foregoing et donc la façon d'avoir le plastic du mod :)
