### ISSUE TITLE
[Typo]: Nom du spell dans la quête du Psimetal

### ISSUE THREAD

**Issue by Blackalf14** [MLDEG/Ragnamod_VII#114]
### Modpack version

7.1.4

### Where is the typo located?

Dans la quête du Psimetal le sort est nommé "Trick:Infusion" au lieu de "Trick: Infusion" (il manque donc un espace)

**Comment by Blackalf14** [comment]
D'ailleurs, je sais que c'est hors-sujet mais j'ai trouvé un bug + un fix sur le Digital Mob Agonizer.

Le problème c'est que je ne vois pas facilement comment l'expliquer sans visuel, je comptais donc peut-être faire une mini-vidéo sur le sujet pour que cela plus simple à comprendre.

C'était pour savoir si cela ne te dérangeait pas, si j'uploadais une vidéo dans un report si je ne trouve pas de meilleur moyen de l'expliquer en texte. 

Bonne journée, soirée, nuit! 🙃

**Comment by MLDEG** [comment]
tu peux
