### ISSUE TITLE
[Bug]:  Craft d'une chicken shell qui ne se lance pas 

### ISSUE THREAD

**Issue by SmaxKiller** [MLDEG/Ragnamod_VII#116]
### Modpack version

7.0.12

### Description

![2024-03-28_19 16 21](https://github.com/MLDEG/Ragnamod_VII/assets/165317960/ee32e870-ed88-4f44-afeb-492722fc908a)
Bonjour !
Je ne parviens pas à lancer le craft d'une chicken shell, tous les éléments sont bons et placés au bon endroit (sauf cécité de ma part). L'Hephaestus Forge contient bien 200 d'Aureal, et d'expérience, ainsi qu'une âme, et 0 blood. Je fais bien clic droit avec un gavel mais rien ne ce passe.  

J'ai essayé de replacer les éléments de craft, ainsi que de détruire et replacer la forge mais rien n'y fait, je suis bloqué. 
Merci pour votre aide. 

### Steps to reproduce

Je place les éléments requis pour le craft que ce soit sur les pedestals ainsi que dans la forge, je clique droit sur la forge avec un gavel mais rien ne se passe. 

### Expected behavior

Le craft devrait se lancer

**Comment by filosofeTHElama** [comment]
Bonjour

Je dispose aussi du même problème, mais avec d'autres recettes (ex: Mending)

Le problème est survenu après que j'ai migré de version du modpack (7.0.11 => 7.1.6)
Même après reconstruction du multiblock et faire des essaie sur une autre save, rien n'y fait...

Dès que possible, je passe sur l'Advanced forge.

J'estime que cette issue est fermée car non reproductible...

**Comment by MLDEG** [comment]
Le problème viens de votre Gavel ou de votre structure qui n'est pas correct car il n'y a pas de problème avec la forge ;)

**Comment by filosofeTHElama** [comment]
J'y ai pas pensé, je vais voir...

...

Ah, haha, HAHAHHAHAHAHAHA

![gavel](https://github.com/MLDEG/Ragnamod_VII/assets/61240546/bdeed0d8-cbb8-466d-9eb6-879b75f72967)

C'est nouveau ça...
Je me sens très idiot maintenant

Mais il vaut mieux ça que de rester bloquer des heures

Merci pour la remarque, dans l'espoir que ça puisse en aider d'autres !
