### ISSUE TITLE
[Bug]: Chargement des chunk

### ISSUE THREAD

**Issue by CalibenQC** [MLDEG/Ragnamod_VII#121]
### Modpack version

7.1.5

### Description

Bug connus: au bout d'un certain temps les chunk ne charge plus et quand ils charge parfois les chest de lootr ne sont pas généré mais un chest ordinaire est généré a la place. J'ai désactiver lootr et les chunk se sont remis a charger normalement.

### Steps to reproduce

se rendre a la frontier des chunk qui ne charge pas et fermer le jeu
faire une copie de la save qui ne charge plus les chunk pour éviter des corruption sur la map
désactiver/dinstaller lootr
lancer le jeu
retourné a la frontiere des chunk qui ne charge plus et constater qu'ils charge de nouveau

### Expected behavior

en désactivant/déinstallant lootr les chunk devrais recommencer a charger sans problème

### Anything else to note?

oui j'ai modifier ton modpack mais c'étais pour la bonne cause pour trouver la source de ce bug

**Comment by MLDEG** [comment]
Serveur ou local ?

Car le problème existe sur Server et non sur le local

**Comment by CalibenQC** [comment]
En local, mais avant la désactivation du mod il me fallait attendre 107 ans avant qu'un chunk daigne se charger et après la désactivation je retrouvais un chargement proche du vanilla

**Comment by MLDEG** [comment]
Du coup il faudra report a LootR et pas ici :)
Car le problème de chunk qu'on a rencontré plusieur fois en live était sur server, et une fois la map en local je n'avais pas le problème.
