### ISSUE TITLE
[Bug]: Crash a cause du mod ae2wtlib

### ISSUE THREAD

**Issue by MickaelMoon** [MLDEG/Ragnamod_VII#123]
### Modpack version

7.1.5

### Description

J'obtiens de manière régulière un crash qui apparemment viendrait du mod Ae2WTLib, je ne sais pas comment cela ce produis c'est souvent en ouvrant l'inventaire de quelque chose une machine ou autre.
En tout cas sur les 6 derniers jours j'ai eu 10 crash avec le même mod a chaque crash
![image](https://github.com/MLDEG/Ragnamod_VII/assets/60145073/56e472cc-78fe-44b1-9e4f-9ca53dbb0555)

### Crashlogs

https://hastebin.com/share/cilowedaga.yaml

### Steps to reproduce

Je ne fais rien de spécial parfois cela arrive en ouvrant l'inventaire d'une machine pneumaticraft, parfois mon stockage ae2, parfois du stockage d'occultisme, et parfois en ouvrant mon inventaire.

### Expected behavior

Ne pas crash

**Comment by SNEAXIII** [comment]
J'ai eu le même problème 2 fois mais je ne peux pas le reproduire non plus :/

**Comment by MLDEG** [comment]
Tu devrais report le bug chez Ae2WTLib, car je ne vois pas où est le problème et il est impossible pour moi de le reproduire.
