### ISSUE TITLE
[Bug]: CofH Honey missing from all recipes

### ISSUE THREAD

**Issue by upd0g1** [MLDEG/Ragnamod_VII#125]
### Modpack version

7.1.6

### Description

Using hive hoppers yields CofH honey, but this fluid has no interactions, recipes, or conversions. 

### Steps to reproduce

1. Place Thermal Series Hive Hopper block
2. Place any bee nest or beehive on top
3. Supply the hive with bees, and the bees with a flower
4. Hive hopper will extract honey as a fluid 
5. Make any attempt to use the honey obtained through the Thermal Series Hive Hopper

### Expected behavior

CofH honey should interact with any recipes involving honey, or have a conversion recipe.

**Comment by MLDEG** [comment]
Fix in 7.1.7 :)
