### ISSUE TITLE
[Bug]: Oculus crash ( i need this mod for my shaders)

### ISSUE THREAD

**Issue by GabberDance** [MLDEG/Ragnamod_VII#129]
### Modpack version

Ragnamod 7 1.18.2 FORGE 40.2.21

### Description

Oculus mod crash at the launcher startup ( i need this mod for my shaders)

### Steps to reproduce

.

### Expected behavior

.

**Comment by MLDEG** [comment]
Ragnamod VII was not designed to play with Shaders.
If you want to make Occulus work, remove the Rubidium mod which automatically installs with it.
Normally Embeddium is compatible, but you risk having a lot of problems playing with a mod not designed to be compatible with the modpack.
