### ISSUE TITLE
[Bug]: Connection Lost when I fight the Spider Boss in Blue Skies in singleplayer

### ISSUE THREAD

**Issue by Anlaiko** [MLDEG/Ragnamod_VII#131]
### Modpack version

7.1.7

### Description

Sorry, I write english very bad, I go to write in french (and autotraduction after the french version).

Bonjour,

Je rencontre un crash lorsque je rentre dans la salle du second boss de la dimension Everdawn du mod Blue Skies.
C'est après un cours instant en entrant dans la salle du boss que j'ai une déconnexion forcée avec le message "Connexion Lost". Pourtant, juste avant la déconnexion, le boss bouge en me regardant mais ne prend pas de dégâts étant dans sa phase de "chargement" (phase équivalente au premier boss).

A chaque reconnexion, après un cours moment, je me faisais à nouveau déconnecter, que ce soit en bougeant ou en restant fix, en essayant de taper le boss ou en ne faisant rien.

Lors de ma dernière connexion, ayant une pierre de téléportation sur moi, j'ai pu l'utiliser ce qui a résolu le soucis dans l'immédiat, mais le problème se pose dans le sens où on a besoin de tuer ce boss pour finir les quêtes de la section Blue Skies.

Merci à vous et bonne journée !
Au plaisir de rejouer à vos modpacks, ils sont géniaux.

-- English (Google traduction)

Good morning,

I encounter a crash when I enter the room of the second boss of the Everdawn dimension of the Blue Skies mod.
It's after a short while entering the boss room that I have a forced disconnection with the message "Connection Lost". However, just before disconnection, the boss moves while looking at me but does not take damage being in its "charging" phase (phase equivalent to the first boss).

Each time I reconnected, after a short while, I would get disconnected again, whether by moving or staying stationary, by trying to hit the boss or by doing nothing.

During my last connection, having a teleportation stone on me, I was able to use it which solved the problem immediately, but the problem arises in the sense that we need to kill this boss to finish the quests in the Blue Skies section.

Thank you and have a good day !
Looking forward to playing your modpacks again, they are awesome.

### Crashlogs

https://hastebin.com/share/jibilunive.perl

### Steps to reproduce

1. Entrer dans le second donjon ;
2. Récolter les 4 clés nécessaires à l'ouverture de la salle du boss ;
3. Cliquer pour entrer dans la salle du boss avec les clés en main ;
4. Attendre quelques secondes l'initialisation du boss ;
5. Le crash survient et nous redirige dans le menu de la liste des serveurs (alors que je suis en mode singleplayer).

-- English (Google traduction)

1. Enter the second dungeon;
2. Collect the 4 keys needed to open the boss room;
3. Click to enter the boss room with the keys in hand;
4. Wait a few seconds for the boss to initialize;
5. The crash occurs and redirects us to the server list menu (while I am in singleplayer mode).

### Expected behavior

Pouvoir combattre et tuer le boss.

-- English (Google traduction)

Being able to fight and kill the boss.

### Anything else to note?

Dans mon inventaire à ce moment là j'avais :
- une épée du mod Blue Skies, 
- une pioche du même mod, 
- une épée en netherite, 
- une pioche en netherite, 
- une warp stone,
- un dank 6
- une multitude de currios,
- un sac avec d'autres sacs dedans.

-- English (Google traduction)

In my inventory at that time I had:
- a sword from the Blue Skies mod, 
- a pickaxe of the same mod, 
- a netherite sword, 
- a netherite pickaxe, 
- a warp stone,
- a dank 6
- a multitude of currios,
- a bag with other bags in it.

**Comment by MLDEG** [comment]
Salut !

Il me faudrait un log ou un crash log quand tu as déconnexion pour voir d'où peut venir le problème :)

**Comment by Anlaiko** [comment]
Salut !

Bien sûr, vous sauriez où je pourrez trouver ça s'il vous plait ?

**Comment by MLDEG** [comment]
My bad, je n'avais pas vu le log déjà fournit !
Du coup le crash vient bien du boss en question, il tick pour X raison.
Et malheureusement moi, je ne vais rien pouvoir y faire, il faudrait le report à Blue Skies pour avoir potentiellement plus d'info.

Sinon, je peux proposer l'idée de supprimé la dimension et de retenté de le trouver, peut-être qu'il y aura une différence.

**Comment by Anlaiko** [comment]
D'accord, quand je pourrais j'essayerais et je vous tiendrais au courant.

Je dois également prendre le temps de faire un report au créateur de Blue Skies mais ça sera fait.

Merci pour les réponses rapide ^^

**Comment by Anlaiko** [comment]
Bonsoir MLDEG,

Même en ayant le poste fermé, je reviens sur le fait de supprimer le monde et le recharger en jeu, ça ne fonctionne pas, mais le soucis semble ne pas venir de l'araignée en elle même mais des actions qu'elle fait, car j'ai pu la tuer à coup de patience, de reconnexion et évidement d'épée.

Il ne me reste plus qu'à aller report sur la page du mod directement.

Merci beaucoup et bonne continuation ^^
