### ISSUE TITLE
[Bug]: Duplication de liquide avec un Fluid Drawer

### ISSUE THREAD

**Issue by filosofeTHElama** [MLDEG/Ragnamod_VII#132]
### Modpack version

7.1.7

### Description

J'ai appris à mes dépends une manière de dupliquer les liquides.
Cela transforme l'objet main libre en sceau vide et on conserve le sceau du liquide utilisé.
J'ai malheureusement perdu un excellent Shield dans le process...

### Steps to reproduce

1. Placer un Fluid Drawer vide et avoir un objet en main libre (shield)
2. Utiliser un sceau de n'importe quel liquide (eg. Milk)
3. (Répéter 2)

### Expected behavior

L'objet main libre reste le même et le sceau est bien vide après utilisation.

**Comment by MLDEG** [comment]
Hélas, c'est un problème venant du mod Functional Storage, a ce niveau, je ne peux rien faire à part supprimer les drawers de fluid, ce qui me semble dommage :(
Il faudrait report le problème directement sur le mod :)
