### ISSUE TITLE
[Bug]: Crafting a netherrack chicken doesn't complete the corresponding quest

### ISSUE THREAD

**Issue by Valeox** [MLDEG/Ragnamod_VII#133]
### Modpack version

7.1.7

### Description

Upon crafting a netherrack chicken, instead of validate the corresponding quest, it does nothing

### Steps to reproduce

Just craft a netherrack chicken

### Expected behavior

It should validate the quest

### Anything else to note?

![image](https://github.com/MLDEG/Ragnamod_VII/assets/92593915/7501b1ea-2387-4baa-86e2-0b2c14631c77)
![image_2024-06-09_174305182](https://github.com/MLDEG/Ragnamod_VII/assets/92593915/4866506c-b9fe-45d3-a8ba-54f144e10c4d)

**Comment by MLDEG** [comment]
I just tested on a creative world with the same version as you and I have no detection problems.
You probably don't have the right questbook, I advise you to uninstall the modpack and reinstall it :)
