### ISSUE TITLE
[Bug]: Tag  chicken crash pipez filtre 

### ISSUE THREAD

**Issue by Qwaze-1** [MLDEG/Ragnamod_VII#136]
### Modpack version

7.1.7

### Description

J'ai voulu ajouter en filtre pipez le tag #chickens:chickens qui regroupe l'ensemble des poulets mais dès qu'on termine de taper le tag le jeu crash et si on relance la partie le joueur devient invisible et toutes les actions ne se voient pas (casser, les item par terre, les changements lorsque que le cable pipez est en extract après je n'ai pas rejoué dessus et ai lancé une backup pour re jouer normalement) et bien évidement le jeu crash à chaque fois qu'on mets le tag dans le filtre j'étais dans la dimension du void lorsque cela c'est produit 

### Crashlogs

https://hastebin.com/share/exewupoqej.perl

### Steps to reproduce

j'étais dans la dimension du void où j'ai installé ma base je voulais faire un reproducteur automatique à poulet et je comptais utiliser les filtres de pipez avec un tag que tous les poulets ont qui est #chickens:chickens sauf que lorsque je fini de taper le tag le jeu crash à chaque fois 

### Expected behavior

si on relance la partie elle est bugé dans le sens ou le joueur devient invisible (non effet de potion) l'action de casser un block n'as plus d'animation les items qui drop sont invisible et j'ai tenté de me /kill pour tester si cela allait aider au final j'ai juste dupliquer 3 item qui était dans mes curios slot et 3 des 4 item que j'avais drop sur les boss de blue skies (les amulettes qu'on mets dans les slots prévue pour)

### Anything else to note?

Après test j'ai l'impressions que ce bug ne se produit uniquement dans la dimension du void

**Comment by MLDEG** [comment]
Malheureusement c'est un bug de Chicken et non Pipez, il faudrait le report a Chicken mais je suis quasi certain que rien ne sera fait :(
