### ISSUE TITLE
[Bug]: Crash on startup due to PSI and its dependency (Magic PSI)

### ISSUE THREAD

**Issue by does-not-equal** [MLDEG/Ragnamod_VII#137]
### Modpack version

7.1.7

### Description

It looks like the PSI mod is causing my game to crash on boot. I have removed it and its dependency (Magic PSI) and it was able to boot successfully.

### Crashlogs

https://pste.ch/sequhaqena.md

### Steps to reproduce

Open game with no mods disabled (crash);
Disable PSI and its dependency (Magic PSI) and boot game;
Opens fine

### Expected behavior

I usually expect the game to load with no crashes ;)

**Comment by MLDEG** [comment]
As you said in your message, the problem comes from PSI, so it would be necessary to report it to them, because for my part I am unable to redo this crash to find out more.
