### ISSUE TITLE
NeoForge ?

### ISSUE THREAD

**Issue by enzofrnt** [MLDEG/Ragnamod_VII#141]
### Describe the feature

Passer sur NeoForge

### Reasons why this should be added

Pour des meilleures performances et une meilleure étique

**Comment by MLDEG** [comment]
Alors va falloir se renseigner avant de dire ce genre de chose :)
Tous les mods utilisé sur ce modpack ne sont pas dispo sur Neforge.
ET SURTOUT, l'information la plus importante, Neoforge n'existe pas en 1.18.2 ;)

Néanmoins, sache que je passerai à Neoforge pour les versions 1.21 ++

**Comment by enzofrnt** [comment]
> Alors va falloir se renseigner avant de dire ce genre de chose :)
> 
> Tous les mods utilisé sur ce modpack ne sont pas dispo sur Neforge.
> 
> ET SURTOUT, l'information la plus importante, Neoforge n'existe pas en 1.18.2 ;)
> 
> 
> 
> Néanmoins, sache que je passerai à Neoforge pour les versions 1.21 ++

Salut,je n'avais pas conscience de tout ça. Merci pour l'info !
Bonne continuation ML.
