### ISSUE TITLE
[Bug]: le craft des biblio d'apotheosis a des problèmes lorsqu'on le fait depuis la table de craft du storage accessor d'occultism

### ISSUE THREAD

**Issue by sprigan0** [MLDEG/Ragnamod_VII#15]
### Modpack version

7.1.0

### Description

Lorsque je clique sur le '+' depuis JEI pour faire apparaitre le craft des hellshelf (et les ranges superieurs de cette table) dans ma table de craft du storage accessor d'occultism, il ne se passe rien. (Aucun item ne se place).
Encore mieux, en réalisant le craft des hellshelfs, la potion de régénération qui devrait être consommer est à la place changé par une potion de regen de niv 2.
Mais aucun avec une table de craft vanilla.

### Steps to reproduce

Faire les craft des biblio d'apoteosis en placant les items manuellement dans la grille de craft du storage accessor d'occultism.

### Expected behavior

-Faire apparaitre les items dans la grille de craft via le '+' de JEI
-Consommer la potion lors du craft

**Comment by MLDEG** [comment]
C'est donc un problème de mob et non modpack ;)
