### ISSUE TITLE
[Bug]: Error loading : Custom Machinery

### ISSUE THREAD

**Issue by CPaulMF** [MLDEG/Ragnamod_VII#16]
### Modpack version

7.1.0

### Description

Losrque je lance le modpack que j'ai installé aujourd'hui. j'ai une erreur avec custom machinery. pourtant je n'ai toujours pas toucher les machines custom. Le jeu ne ce lance pas et m'indique l'erreur avant même l'écran titre. J'ai essayé de désinstaller et réinstaller puis non toujours la meme erreur

### Crashlogs

[crash-2024-01-21_19.08.03-fml.txt](https://github.com/MLDEG/Ragnamod_VII/files/14003354/crash-2024-01-21_19.08.03-fml.txt)

### Steps to reproduce

Je lance le jeu et il crash.

### Expected behavior

s

**Comment by CPaulMF** [comment]
Bonjour, je vois que le billet a été fermé. J'aimerais savoir si j'ai fais une erreur dans mon signalement ? Je me retrouve quand même avec un souci qui m'empêche de jouer. Je suis ne suis pas au bonne endroit, est ce possible de m'indiqué la procédure pour faire les chose dan l'ordre ?

**Comment by MLDEG** [comment]
D'une il faut lire :
If you have a crash logs, please post it here. please use https://pste.ch/, or https://hastebin.com/
De deux, si je n'ai pas de problème de mon coté, c'est que le problème vient du tien, donc il faudra voir avec la communautée sur Discord pour t'aider.
Ce n'est pas méchant, mais je ne peux plus me permettre de faire du cas par cas en fonction des configs de chacun, je vais devenir fou à force.

**Comment by CPaulMF** [comment]
Merci pour la réponse. Je comprend ta situation. Je n'ai pas l'habitude de faire des reports alors désolé de ma maladresse. Je vais tenté de voir sur discord. Cordialement, un homme nul avec les ordis.  @MLDEG
