### ISSUE TITLE
[Bug]: Solide nuclear waste recipe not working

### ISSUE THREAD

**Issue by zelytra** [MLDEG/Ragnamod_VII#17]
### Modpack version

7.1.0

### Description

When connecting a Chemical crystallizer to a Ultimate pressurized pipe full of spent nuclear wast gaz, the machine is not filling with the gaz in question and so not crafting the solid nuclear wast. Locking chicken quest and so on.

### Steps to reproduce

1. Place a Chemical Crystallizer from Mekanisme
2. Connect it on any side the ultimate pressurized pipe full of spent nuclear wast
3. Observing nothing entering in the machine

### Expected behavior

Should produce solid nuclear waste

**Comment by MLDEG** [comment]
![2024-01-22_12 22 11](https://github.com/MLDEG/Ragnamod_VII/assets/90324978/b2ef1afa-d474-41d7-8fce-c3c1461b10d9)
![2024-01-22_12 22 13](https://github.com/MLDEG/Ragnamod_VII/assets/90324978/0cde2225-34b6-4066-b8d6-ecb3d4e3ce31)

**Comment by zelytra** [comment]
wrong machine, i'm talking about this machine.
![image](https://github.com/MLDEG/Ragnamod_VII/assets/72125876/75220533-a0bb-45ac-9510-af8cb8f0be12)

Btw, you can just let people closing issue by them own if you confirm is not relevant or well explianed. Closing like this the issues is just making a stop to a conversation. Or just taging them `not relevant`

**Comment by MLDEG** [comment]
So you're telling me that you're in 7.1.0 while on 7.1.0 this craft was replaced by the new one that I showed above?!
And you want me to keep your "issue" open when there is no problem?!
Bruh

If I close an issue it means that there is no problem, that it is fixed or that it is not a modpack issue but a mod issue.
So I confirm that the craft of Solid Nuclear Waste works and that there is currently no issue like this on 7.1.0
![Capture d'écran 2024-01-22 185706](https://github.com/MLDEG/Ragnamod_VII/assets/90324978/3967388d-f150-415c-b9d7-721a2969d3f5)

**Comment by zelytra** [comment]
![image](https://github.com/MLDEG/Ragnamod_VII/assets/72125876/c2bc18fa-38b9-4c13-b73b-0397d7537959)
I'm in 7.1.0, and the recipe is still theire

**Comment by MLDEG** [comment]
This is simply not possible unless you installed the update incorrectly...

**Comment by MLDEG** [comment]
https://github.com/MLDEG/Ragnamod_VII/commit/6fcdf9a3e34a7b0d1235637d15819f53c72f1c72
