### ISSUE TITLE
[Typo]: QuestBook / Spirit / Crude Soul Crystal

### ISSUE THREAD

**Issue by Warognard** [MLDEG/Ragnamod_VII#18]
### Modpack version

7.1.0

### Where is the typo located?

In the Spirit chapter, the quest labbeled "Crude Soul Crystal" has in description the word "upgrade" wrote as "updrage"

### Fix

![image](https://github.com/MLDEG/Ragnamod_VII/assets/46192680/1fa0f370-e88d-4b4a-9d78-334a40382456)

**Comment by MLDEG** [comment]
Thanks, this will be fixed
