### ISSUE TITLE
[Bug]: Craft Wire Multiservo Press consume Wireworking Die

### ISSUE THREAD

**Issue by sky-1362** [MLDEG/Ragnamod_VII#21]
### Modpack version

7.1.0

### Description

quand je craft des Wire dans le Multiservo Press il consomme le Wireworking Die

https://github.com/MLDEG/Ragnamod_VII/assets/157504210/de6acce9-2113-4f15-8543-f8729759170f

### Steps to reproduce

Essayer de crafter un Wire dans le Multiservo Press avec le Wireworking Die

### Expected behavior

Le Wireworking Die ne devrait pas se consommer

**Comment by h1503** [comment]
Bonjour j'ai le même problème avec la rodworking die.

**Comment by MLDEG** [comment]
Ce sera fix merci :)
