### ISSUE TITLE
[Bug]: Crafting a creative glazed hopper botany pot will not validate the appropriate quest

### ISSUE THREAD

**Issue by Valeox** [MLDEG/Ragnamod_VII#22]
### Modpack version

7.1.0

### Description

Any creative hopper botany pot crafted except for the one that's displayed in the quest book doesn't validate the quest

### Steps to reproduce

Just craft a creative hopper botany pot but not the one that's showed in the quest

### Expected behavior

It should validate the quest

### Anything else to note?

![image](https://github.com/MLDEG/Ragnamod_VII/assets/92593915/5f8d0517-373a-4eb2-99f5-9dca217ebc58)
![image](https://github.com/MLDEG/Ragnamod_VII/assets/92593915/9b967e38-1708-4a97-ab72-63c6a4dbe4f7)

**Comment by MLDEG** [comment]
Will be fixed in the next update :)
Thank you !
