### ISSUE TITLE
[Bug]: rocket multiplication

### ISSUE THREAD

**Issue by IsarielD** [MLDEG/Ragnamod_VII#23]
### Modpack version

7.1.0

### Description

Shift-striking a rocket (tier 1 for sure, above not tested) with a tinker pickaxe improved with luckier drops two rockets that are fully usable (not a visual glitch)

### Steps to reproduce

1. Place a T1 rocket on its pad
2. Improve a tinker pickaxe with luckier
3. Shift-strike the rocket as if to pick it up
4. Two rockets drop

### Expected behavior

4. Only one rocket should drop

### Anything else to note?

❤️

**Comment by MLDEG** [comment]
Yep, it's a known bug, even without luck it seems to me that it also duplicates :/
Given the ease of crafting rockets, this doesn't pose a problem :)
The bug comes from Beyond Earth!
