### ISSUE TITLE
[Bug]: Framed Drawer + Mekanism

### ISSUE THREAD

**Issue by ElKhajiitos** [MLDEG/Ragnamod_VII#25]
### Modpack version

7.1.0

### Description

J'ai tenté de craft (depuis mon Wireless Crafting Terminal de AE2 si c'est important) un Framed Drawer 1x1 de Functional Storage en utilisant un Black Plastic Block et un White Plastic block (tout deux de Mekanism), ça a causé un crash, et une fois reconnecté tout un tas de problème d'affichages

Quelques exemples :
![Screenshot_1](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/24cce357-a785-4134-860e-b114825355d1)
![Screenshot_2](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/bb7ecc28-5bff-466f-b184-de4d821c6d47)
![Screenshot_3](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/060d100c-0e24-4f5c-b87a-27e134b9af29)
![Screenshot_4](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/53457115-3636-484c-ae61-88fea7e2c439)
![Screenshot_5](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/04bc062c-2b50-46e9-876c-355a40c2ca94)

Je ne sais pas s'il y a quoi que ce soit que tu puisses faire, c'était assez inattendu en tout cas
Merci, bon jeu

### Steps to reproduce

Black Plastic Block en haut à gauche, White Plastic Block en haut au milieu et Framed Drawer 1x1 en haut à droite du craft

### Expected behavior

Un framed drawer texturé

### Anything else to note?

Relancer le jeu corrige les bugs d'affichages

**Comment by MLDEG** [comment]
Il faut lire le quest book :)
