### ISSUE TITLE
Configurer Nature's Aura sur plus de dimensions (Blue Skies...)

### ISSUE THREAD

**Issue by MapperTV** [MLDEG/Ragnamod_VII#26]
### Describe the feature

Salut, comme vu en live tout à l'heure, ajuster les dimensions Blue Skies (Everbright, Everdawn) pour qu'elles aient l'aura de type "overworld".
Éventuellement voir si d'autres dimensions pourraient aussi être configurées, genre Alfheim etc (je n'ai pas la liste des dimensions en tête, tu en sauras surement plus que moi).

Merci!

### Reasons why this should be added

Pour plus de cohérences (dimension pleines d'éléments naturels) et de possibilités de jeu.

**Comment by MLDEG** [comment]
Prochaine maj je les ajouterais :)
