### ISSUE TITLE
[Typo]: Tooltips on Dimensional Shard Ore 

### ISSUE THREAD

**Issue by Bagra67** [MLDEG/Ragnamod_VII#27]
### Modpack version

7.1.0

### Where is the typo located?

Tooltips:
![image](https://github.com/MLDEG/Ragnamod_VII/assets/65661423/a0bdcb57-af80-476d-a4b1-6886017414a2)

### Fix

Remove the second "spawn" word

**Comment by MLDEG** [comment]
This will be fixed :)
