### ISSUE TITLE
[Bug]: crash a cause du mod embedium 

### ISSUE THREAD

**Issue by kilxy17** [MLDEG/Ragnamod_VII#28]
### Modpack version

7.1.0

### Description

j'ai voulu personnaliser un stack de framed drawer de fonctional storage et au moment au j'ai mit le stack de framed drawer dans le slot correspondant dans ma table de craft, après avoir mit 1 stack de inlaid blackstone de chipped dans le premier slot et 1 stack de inlaid netherrack de chipped dans le deuxième slot, mon monde a crash et me dit que embedium,rubidium a potentiellement crée le crash.

### Crashlogs

https://bytebin.lucko.me/7PrpKtBg5M

### Steps to reproduce

j'ai voulu personnaliser un stack de framed drawer de fonctional storage dans la table de craft 2*2 de mon invetaire et au moment au j'ai mit le stack de framed drawer dans le slot correspondant dans ma table de craft, après avoir mit 1 stack de inlaid blackstone de chipped dans le premier slot et 1 stack de inlaid netherrack de chipped dans le deuxième slot, mon monde a crash et me dit que embedium,rubidium a potentiellement crée le crash.

### Expected behavior

au lieu de crash, j'aurais du voir un apprecu de mon drawer personaliser sur la sortie de mon craft et j'aurais du pouvoir recupere les craft

**Comment by MLDEG** [comment]
Il faut lire le quest book ...
