### ISSUE TITLE
[Bug]: Tinker modifier wrenching

### ISSUE THREAD

**Issue by Samnnes** [MLDEG/Ragnamod_VII#29]
### Modpack version

7.1.0

### Description

Le modifier wrenching sur un outlie tinker example une pickaxe ne function pas avec pipez mais si on fait une wrench de tinker elle est fonction avec pipez. 

### Steps to reproduce

Faire n'importe qu'elle outile tinker sauf la wrench avec le modifier wrenching

### Expected behavior

Pouvoir utiliser le modifier wrenching pour pipez

**Comment by MLDEG** [comment]
Il faudra le report à Tinker, je n'ai pas la main là-dessus.
