### ISSUE TITLE
[Bug]: Deluxe Cheeseburger Craft

### ISSUE THREAD

**Issue by Bagra67** [MLDEG/Ragnamod_VII#30]
### Modpack version

7.1.0

### Description

The Deluxe Cheeseburger use to make Neutron Burger doesn't accept Cabbage from Croptopia but accept all other cabbage:
From Farmer's Delight
![image](https://github.com/MLDEG/Ragnamod_VII/assets/65661423/73caf9bd-ac69-4906-bfc9-0ea7103c34cf)
From Croptopia:
![image](https://github.com/MLDEG/Ragnamod_VII/assets/65661423/f98f5785-8e6e-4afc-b57a-1355d8d3d6a0)

It looks like croptopia cabbage doesn't have the tag: forge:salad_ingredients

### Steps to reproduce

Screenshot should have all the necessary information to reproduce the bug,

But:
1: Check Deluxe Cheeseburger craft
2: Try to make one with croptopia cabbage: KO

### Expected behavior

Croptopia Cabbage should be used to make the Deluxecheeseburger

### Anything else to note?

I really appreciate the endgame of the pack, and all the pack !

**Comment by MLDEG** [comment]
Will be fix in the next update :)
