### ISSUE TITLE
[Bug]: Taco Craft

### ISSUE THREAD

**Issue by Bagra67** [MLDEG/Ragnamod_VII#31]
### Modpack version

7.1.0

### Description

The Taco use to make Neutron Taco acceptonly one kind of Cheese from Croptopia 
![image](https://github.com/MLDEG/Ragnamod_VII/assets/65661423/9d71abda-19f7-4917-965a-d9d6a20b9c1b)
Other Cheese:
![image](https://github.com/MLDEG/Ragnamod_VII/assets/65661423/a4cdcd75-8a93-4d8f-8341-d59988a971e4)

### Steps to reproduce

Screenshot should have all the necessary information to reproduce the bug,

But:
1: Check Taco craft
2: Try to make one with for exemple Beyond Earth cheese: KO

### Expected behavior

All kind of cheese should be accepted
(Beyond Earth, Croptopia, Thermal Cultivation)

**Comment by MLDEG** [comment]
Will be fix in the next update :)
