### ISSUE TITLE
[Bug]: Cabbage Seed from Farmer's Delight

### ISSUE THREAD

**Issue by Bagra67** [MLDEG/Ragnamod_VII#32]
### Modpack version

7.10

### Description

Wrong seed is obtain:
![image](https://github.com/MLDEG/Ragnamod_VII/assets/65661423/78be4a37-0168-4d28-a781-b0ec8f7ade3e)

### Steps to reproduce

Put a cabbage from Farmer's Delight in your crafting table

### Expected behavior

Should be obtain:
![image](https://github.com/MLDEG/Ragnamod_VII/assets/65661423/c7e880db-04ec-422e-8d24-f36c12d40ed2)

**Comment by MLDEG** [comment]
Will be fix in the next update :)
