### ISSUE TITLE
[Bug]: Formation plane from AE2 acting up weirdly

### ISSUE THREAD

**Issue by IsarielD** [MLDEG/Ragnamod_VII#33]
### Modpack version

7.1.0

### Description

[probable mod issue]
On my private server as well as on solo worlds, the formation plane from AE2 does not place blocks/items in world

Except at some random times : only once the FP placed a block the moment i set up the filter while the one beside did not

### Steps to reproduce

1. create a AE network : ME controller, storage bus on a chest, formation plane
![image](https://github.com/MLDEG/Ragnamod_VII/assets/157652549/2ff1b87c-6432-4bae-a09a-25043c0ab46a)
2. add a filter to the FP for some blocks
![image](https://github.com/MLDEG/Ragnamod_VII/assets/157652549/1d26d54c-3eef-425f-88af-6add47c2fe6e)
3. put these blocks in the chest
![image](https://github.com/MLDEG/Ragnamod_VII/assets/157652549/735b3079-7545-4dee-b008-bdfe5b2d51a3)

### Expected behavior

the FP should be placing these blocks in front of itself

### Anything else to note?

isnt AE2 annihiliation plane supposed to have have a UI for filtering ?!?

**Comment by Bagra67** [comment]
The formation plane doesn't place item that already in your AE
But only new item that enter the network
Don't know if it's clear :'(

**Comment by IsarielD** [comment]
Is that a new change ? :o 
I remember using these to autocraft livingrock/wood in ragnamod 6

**Comment by MLDEG** [comment]
You need to use Import Bus and not Storage Bus :)
