### ISSUE TITLE
[Bug]: Creative Source Jar

### ISSUE THREAD

**Issue by weberlepecheur** [MLDEG/Ragnamod_VII#36]
### Modpack version

7.1.0

### Description

Bonjour,

Il s'agit d'un bug concernant la creative source jar, ce n'est pas dû au modpack mais plutôt au mod Ars Nouveau en lui-même.
Dans le modpack il nous ai donné la possibilité de le craft mais le problème survient lorsqu'il est posé et qu'on veut le récupérer, celui-ci disparait sans laisser d'item derrière lui y compris en ayant toucher de soie. 

### Steps to reproduce

Placer une créative jar source d'ars nouveau
Détruire la créative source jar pour la récupérer

La créative source jar disparait sans rien laisser derrière 

### Expected behavior

L'item créative source jar tombe au sol en tant qu'item a récupérer.

**Comment by MLDEG** [comment]
Ok donc c'est un manque de loot table, je l'ajouterai :)

**Comment by MLDEG** [comment]
Ce sera fix pour la prochaine update :)
