### ISSUE TITLE
[Bug]: AE2 ME Wireless transceiver randomly working and crashing client

### ISSUE THREAD

**Issue by Iansus** [MLDEG/Ragnamod_VII#37]
### Modpack version

7.1.0

### Description

I have an ME Network with 2 ME drives filled on one side, and a powered ME controller connected to a ME Wireless Transceiver with a terminal. The terminal on this side properly displays the ME Network contents.
On the other side (a few blocks away) I have a powered ME Wireless Transceiver and a terminal. 

The transceiver connected to the ME Network is set a broadcaster, and after inputing the name of the channel (public or private), clicking "Save" randomly crashes the client (first bug).

If the client has not crashed, and I put the same configuration (public/public or private/private) on the other transceiver, then:
* Either it shows "AE2 Channels: 0/32" on both sides
* Or it shows "AE2 Channels: 1/32" on both sides but terminal on the far side shows empty contents

I have tried it on solo and MP to no avail...

### Crashlogs

On game crash, see here: https://pastebin.com/MuDxeDtz

On channels set to "0/32", server logs indicate `SecurityConnectionException: Connection failed due to different security realms.`. After some investigation, transceiver have a "security key", which might have been set if one of them has been private at some point. Connection needs for both of them either to have no key, or to have the same. Breaking an replacing the blocks might correct this issue but increase the probability of the crash.

When channels are set to "1/32", even with the "securityAuditLog" enabled in "commons.json" on the server, there is no additional debug message...

### Steps to reproduce

1. Create a basic ME network: power source, ME controller, ME drive, Item storage and a wireless ME transceiver
2. Connect a terminal to your ME network, and put a stack of any one block
3. Set your ME transceiver to broadcaster, channel name "test", security "public", save => **Sometimes crashes here**
4. A few blocks away, create an AE2 energy cell, an energy acceptor and a power source, connect the cell to a wireless ME transceiver
5. Set your second transceiver to subscriber, channel name "test", security "public" save
6. Connect a terminal to your second transceiver, open it, empty contents

### Expected behavior

The second terminal should display the contents of your ME network.

### Anything else to note?

The game crashes more in solo than in MP, see here the setup: 

ME Network:
![image](https://github.com/MLDEG/Ragnamod_VII/assets/1913897/4ae84efe-0d80-4c4f-b5fb-9af1537c65e8)

Remote side:
![image](https://github.com/MLDEG/Ragnamod_VII/assets/1913897/63ff1994-2258-4a07-b256-fd5ecfaaf661)

**Comment by weberlepecheur** [comment]
Je n'ai pas eu le problème de crash mais je n'avais effectivement pas de display sur le contenu de mon network, je l'ai résolu en mettant un dense cable au lieu d'etre coller au ME Controller

![image](https://github.com/MLDEG/Ragnamod_VII/assets/18701493/34cb8618-2ab3-4070-9c60-a0f53d5f72e6)

**Comment by Iansus** [comment]
Pour le premier bug de crash, ça vient du clic sur "Save" avant d'avoir créé un réseau, et du fait que le "delete" est pas pris en compte en live. Côté AE2 donc.

Et pour le reste, j'ai compris le problème : les réseau (grid) AE2 ne se connecte que s'ils n'ont pas de clé de sécurité, ou s'ils ont la même.
J'avais dans mon réseau un Security Terminal pour l'accès via un Wireless Terminal, qui a positionné une clé sur la partie ME Network. La, 2 options : 
* Soit je connectais mon 1er transceiver au réseau existant : sa clé reste à -1, il ne fait pas partie du réseau, d'où le "channels 0/32"
* Soit je le connectais après coup avec un câble : mise à jour de sa clé, et il rejoint le réseau "channels 1/32"

En revanche, pour le transceiver distant, c'était impossible de mettre à jour sa clé pour correspondre à celle du réseau, donc il refusait de fusionner avec le reste.

Donc pour l'instant, les 2 solutions validées pour créer un réseau wireless : 
* Connecter le Security Terminal après avoir positionné les transceivers distants
* Ou bien, a l'ajout d'un nouveau transceiver, le relier en place par cable, puis couper les câbles

**Comment by MLDEG** [comment]
Ça ressemble à problème de mod et non de modpack ;)
Faite le report sur le mod AE Additions pour avoir plus d'infos et peut-être un fix
