### ISSUE TITLE
Crash server face au Boss du Spider Lair de Blue skies (Everdawn)[Bug]: 

### ISSUE THREAD

**Issue by Cherichoux** [MLDEG/Ragnamod_VII#38]
### Modpack version

7.1.0

### Description

Face au boss, le server crash, impossible de récupérer le monde....

### Crashlogs

https://pste.ch/yufumokuda.pl

### Steps to reproduce

Déclencher l'agression du boss du Spider Lair dans l'Everdawn de Blue Skies

### Expected behavior

Je sais pas

### Anything else to note?

Y'en a pas

**Comment by MLDEG** [comment]
Il faudra report à Blue Skies, je n'ai pas la main pour fix ton crash
