### ISSUE TITLE
Description pour le chapitre FTB Industrial Contraptions

### ISSUE THREAD

**Issue by MimifanOfficiel** [MLDEG/Ragnamod_VII#40]
### Describe the feature

Dans le livre de quêtes, là où nous avons tous les chapitres, FTB Industrial Contraptions est le seul à ne pas avoir de description (Exemple Draconic Evolution a pour description "DRAKONIK")

Je viens donc suggérer l'ajout de la description "IC2, but worse." pour ce chapitre.

### Reasons why this should be added

Cette proposition est pensée par rapport au fait que le mod FTB Industrial Contraptions est très clairement une version moins intéressante de Industrial Craft 2, l'énergie n'étant pas compatible avec les autres, les crafts sont horribles et le mod est globalement inintéressant x)

(Évidemment ce n'est pas l'avis de tout le monde, mais du coup je trouve que ça rajouterai une nouvelle petite touche d'humour et ce chapitre aura donc une description ^^)

Bonne journée/soirée ! :D

**Comment by MLDEG** [comment]
Non je ne le changerais pas :)

**Comment by MimifanOfficiel** [comment]
Ohhh dommage :(
Mais bon tant pis j'aurai tenté de proposer ^^
Passe une bonne soirée et merci encore pour le pack :D

**Comment by MLDEG** [comment]
Le problème étant que si un des dev venaient à regarder Ragnamod VII, ce serait une insulte directe envers eux et je ne suis pas pour.
Quitte à ne pas aimer un mod autant n'a pas l'ajouter au modpack :)

**Comment by MimifanOfficiel** [comment]
Ahhh oui très bien vu !
My bad je n'avais pas pensé à cette possibilité :)
