### ISSUE TITLE
[Bug]: Create Slice & Dice slicer missing tools 

### ISSUE THREAD

**Issue by KrishGup** [MLDEG/Ragnamod_VII#41]
### Modpack version

7.1.0

### Description

The slicer from Create Slice & Dice seems to only allow knives. It should also allow axes, shovels, pickaxes and shears as these are all tools usable on the cutting board which the slicer is meant to complement.

### Steps to reproduce

1. Place and power a Create Slice & Dice slicer
2. Attempt to right click slicer with affected tool (Tested with iron pickaxe, shovel, axe, shears)
3. Slicer doesn't take toolthe 

### Expected behavior

Expected Behavior: Slicer takes a tool such as an iron axe is able to be used in recipes such as stripping logs, breaking apart amethyst blocks etc.

### Anything else to note?

This issue is similar to the previously fixed issue regarding allowed tools fixed in v7.0.11

**Comment by MLDEG** [comment]
It will be fixed in the next update :)
