### ISSUE TITLE
[Bug]: Creative fluid tank (Create) receipe

### ISSUE THREAD

**Issue by BideoGemu** [MLDEG/Ragnamod_VII#42]
### Modpack version

7.1.0

### Description

![image](https://github.com/MLDEG/Ragnamod_VII/assets/71313676/47e19aee-dcd1-4a60-9240-ea9b6dc960f7)

As shown in the screenshot, craft of the creative fluid tank from create requires destabilized redstone from thermal, which has been replaced by liquid redstone from tikers reforged.

### Steps to reproduce

No step to reproduce this.

### Expected behavior

Replace destabilized redstone bucket for this craft

**Comment by MLDEG** [comment]
will be fix in the next update
