### ISSUE TITLE
[Bug]: Creative Energy Cell

### ISSUE THREAD

**Issue by weberlepecheur** [MLDEG/Ragnamod_VII#43]
### Modpack version

7.1.0

### Description

Problème identique à l'issue #36.

Il s'agit de la Creative Energy Cell de Wormhole (Portals)
Une fois posé, si le bloc est cassé pour être récupérer celui-ci disparait.

### Steps to reproduce

1. Poser le bloc au sol
2. Récupérer le bloc avec (ou non) toucher de soie
3. Le bloc disparait

### Expected behavior

Le bloc est censé pouvoir être récupérer.

**Comment by MLDEG** [comment]
ce sera fix pour la prochaine maj :)
