### ISSUE TITLE
[Bug]: Creative Stuff Quest, Mana Tablet

### ISSUE THREAD

**Issue by BideoGemu** [MLDEG/Ragnamod_VII#44]
### Modpack version

7.1.0

### Description

You just need to have one mana tablet in the inventory to validate the craft

### Steps to reproduce

1. Unlock "Creative Stuff" Quests
2. Unlock creative Mana tablet quest
3. Recover a mana tablet in inventory

### Expected behavior

Normal mana tablet don't validate Creative Mana Tablet Quest

### Anything else to note?

Mana Tablet and Creative Mana Table have "botania:mana_tablet" as identifier, that's why this bug exists I think

**Comment by MLDEG** [comment]
Will be fix in the next update :)
