### ISSUE TITLE
[Typo]: Quêtes Draconic Evolution

### ISSUE THREAD

**Issue by ElKhajiitos** [MLDEG/Ragnamod_VII#46]
### Modpack version

7.1.0

### Where is the typo located?

Dans le chapitre de quêtes de Draconic Evolution les outils Draconic & Chaotic sont juste nommés Draconic/Chaotic Shovel alors que pour le Wyvern c'est bien marqué Wyvern Tools  la description parle aussi seulement de pelles et pas d'outils en général
![Screenshot_1](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/32ed12cd-2e05-4eb6-b7a7-d04878fae5aa)
![Screenshot_2](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/01e2ce10-50c6-4837-9d16-626b01b60039)
![Screenshot_3](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/9be41656-e2d1-4c14-a924-73c60526b881)

### Fix

Changer "Shovel" par "Tools", ainsi que la descriptions de ces derniers

**Comment by MLDEG** [comment]
Ce sera fix pour la prochaine maj :)
