### ISSUE TITLE
[Bug]: Erreur de minage avec le level de minage

### ISSUE THREAD

**Issue by SokenCraft** [MLDEG/Ragnamod_VII#47]
### Modpack version

7.1.0

### Description

Je viens de débuter la partie et quand je mine avec une pioche en pierre des minerais level iron ou diamond il drop alors qu'ils ne devraient pas.

### Steps to reproduce

En minant du bauxite ou même du red beryl gem je les drop alors que je devrais pas avec ma pioche en pierre.

### Expected behavior

Rien ne devrait dropper ou je pense que ce serait écrit level stone au lieu de level iron ou diamond.

**Comment by MLDEG** [comment]
Il y a eu beaucoup de changement dans les tag vis-à-vis de ça entre la 1.16 et la 1.18.
Résultat beaucoup de mod n'ont pas mis à jour leurs blocs ou leurs tags et tout refaire me demanderait beaucoup trop de temps donc ça restera comme ça :)

**Comment by SokenCraft** [comment]
D'accord je voulais juste m'assurer que tu étais au courant ^^
