### ISSUE TITLE
[Bug]: Starting shulker box is deleting items

### ISSUE THREAD

**Issue by SummitSummit** [MLDEG/Ragnamod_VII#48]
### Modpack version

7.1.0

### Description

In the player inventory you can pick up the Shulker Box, hover over a different item, and right-click the item to put it into the Shulker Box.  The problem is once the Shulker Box is full it starts deleting the items you click on.

### Steps to reproduce

In the player inventory pick up the Shulker Box, hover over a different item, and right-click the item to put it into the Shulker Box when the Shulker Box is already full.

### Expected behavior

Once the Shulker Box is full, right-clicking an item should do nothing.

**Comment by MLDEG** [comment]
It's a Quark issue.
I can't do anything :/
