### ISSUE TITLE
[Bug]: duplication de block via create quality of life

### ISSUE THREAD

**Issue by kilxy17** [MLDEG/Ragnamod_VII#49]
### Modpack version

7.1.0

### Description

J'ai un bug de duplication d'inlaid block de chipped (blackstone, netherrack) quand je les ait automatisé via la mason's saw de create quality of life

![2024-02-03_18 01 52](https://github.com/MLDEG/Ragnamod_VII/assets/157801263/45d60955-54a4-4696-b4a8-6872ee2f48bd)
![2024-02-03_18 01 59](https://github.com/MLDEG/Ragnamod_VII/assets/157801263/ab9f2156-41b0-4728-a0de-5014c4e8c161)
![2024-02-03_18 02 03](https://github.com/MLDEG/Ragnamod_VII/assets/157801263/0bf2f0d9-4a3f-4e92-9259-a558ddc5998a)
![2024-02-03_18 02 08](https://github.com/MLDEG/Ragnamod_VII/assets/157801263/8e3e9ef1-c192-4518-b4cf-381cbc0b75f8)
![2024-02-03_18 02 15](https://github.com/MLDEG/Ragnamod_VII/assets/157801263/35450b21-f2fd-4468-bb5c-8bf0ce9be67b)

### Steps to reproduce

1) j'ai crée ma ligne de fabrication d'inlaid blackstone avec create et la mason's saw de create quality of life avec moteur régler sur 256 
2) j'ai mis en automatisation la ligne via un craft applied donc pas automatiquement 
3) j'ai crée le pattern 1 blackstone de minecraft vanilla crée un inlaid blackstone de chipped
4) j'ai lancer un craft de 1000 block

### Expected behavior

le craft aurait du s'arrêter après avoir fait 1000 block 

### Anything else to note?

Edit : il 'y a bien une duplication mais pas infinie , 
j'ai fait mon autocraft 1 block pour 1 block, JEI me montre le craft 1 block pour 1 block, le craft réellement effectuer deviens 1 block crée 22 block

**Comment by kilxy17** [comment]
Edit : il 'y a bien une duplication mais pas infinie , 
j'ai fait mon autocraft 1 block pour 1 block, JEI me montre le craft 1 block pour 1 block, le craft réellement effectuer deviens 1 block crée 24 block

**Comment by MLDEG** [comment]
"via create quality of life" 
Ce sont les mots de ton issue, du coup, ce sera sur create quality of life qu'il faudra report ce bug, pas le modpack qui n'y est pour rien. :)
