### ISSUE TITLE
[Bug]: Endstone & Netherrack Chickens

### ISSUE THREAD

**Issue by ElKhajiitos** [MLDEG/Ragnamod_VII#52]
### Modpack version

7.1.1

### Description

Les poulets Endstone Chicken & Netherrack Chicken ne sont pas détectés pour les quêtes après les avoir fait 
![Screenshot_3](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/702c38ed-30fc-41c1-9d57-b4f565ba7277)
![Screenshot_5](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/83fccb61-4701-46c6-b07e-79e71130ce8c)
![Screenshot_6](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/dd0bf36f-b36a-4f0e-9c7b-efe1935f7002)

### Steps to reproduce

Craft les deux chicken 

### Expected behavior

Validation de quêtes

**Comment by MLDEG** [comment]
Will be fixed :)
