### ISSUE TITLE
[Typo]: Snad quest

### ISSUE THREAD

**Issue by funtique** [MLDEG/Ragnamod_VII#53]
### Modpack version

7.1.1

### Where is the typo located?

Quest 59A524556708186E (Snad in Miscellaneous)

### Fix

It should be cactus not "cacti" I think
![Capture d'écran 2024-02-04 230333](https://github.com/MLDEG/Ragnamod_VII/assets/30874304/f349d24a-d10b-44bd-8337-570c51115e7d)

**Comment by MLDEG** [comment]
https://en.wikipedia.org/wiki/Cactus
