### ISSUE TITLE
[Bug]: Impossible de positionner l'Ethernal Butcher Knife ou Butcher Knife sur le Slicer

### ISSUE THREAD

**Issue by LordDarkWolf** [MLDEG/Ragnamod_VII#54]
### Modpack version

7.1.1

### Description

Bonjour MLDEG, 

Tout d'abord merci pour le boulot!

je n'arrives pas à insérer le Butcher Knife ou le Ethernal Butcher Knife, ni même un simple Knife dans mon Slicer

J'ai essayé toutes les combinaisons de touche, Sneak ou non, rien n'y fait.

![2024-02-04_23 51 21](https://github.com/MLDEG/Ragnamod_VII/assets/33444937/1581f4d2-c5bb-4e70-a781-51dc03ff53ab)

Que puis-je vérifier pour voir ce qui ne fonctionne pas ?

Merci.

### Steps to reproduce

1. Créer un Slicer
2. Le poser n'importe où, connecté ou non
3. Essayer d'insérer un Ethernal Butcher Knife
4. Rien ne se passe

### Expected behavior

L'Ethernal Butcher Knife s'insère dans le Slicer, comme dans ta vidéo n°30 de Ragnamod 7.

**Comment by LordDarkWolf** [comment]
Je viens de regarder les logs et j'ai remarqué cette erreur :
![image](https://github.com/MLDEG/Ragnamod_VII/assets/33444937/377737cc-8f6f-4d30-a2f4-9f2f66107f14)

J'ai commencé la partie durant la beta, aurais-je oublié de modifier ou supprimé certain fichier ?

**Comment by MLDEG** [comment]
Ce sera fix pour la prochaine maj :)
