### ISSUE TITLE
La nouvelle recipe des Chaos Shard est un jeu d'attente

### ISSUE THREAD

**Issue by Blackalf14** [MLDEG/Ragnamod_VII#55]
### Describe the feature

Salut, je viens de check le nouveau craft des Chaos Shard dans la 7.1.1 est après quelque calcul le craft n'a l'air tout simplement pas valable, voici mes recherches:

Considérons que le joueur rush directement le poulet:

Il a donc besoin de 11 Large Chaos Fragment (6 + 5 pour le Chaotic Core)

11 * 9 * 9 = 891 - 1 (récompense de quête) = 890
Il aurait donc besoin de 890 Tiny Chaos Fragment

Étant donné qu'il faut 1000mb de Chaos Liquid pour un Tiny Chaos Fragment est qu'une Chaos Dust produit 10mb de Chaos Liquid:
1000 / 10 = 100
890 * 100 = 89000
Un total de 89000 Chaos Dust est demandé.

A ce moment là nous avons besoin de 5mb d'antimatter et d'une unpredictable dust:

Commençons par l'Antimatter:

89000 * 5 = 445 000
445 000mb d'Antimatter sont donc requis

Étant donné qu'un mb d'Antimatter requiert 1000mb de Polonium qui lui même requiert 10mb de Nuclear Waste:
445 000 * 1000 * 10 =  4 450 000 000 mb de Nuclear Waste

Nous pouvons considérer les poulets hors-jeu car:

Un roost de 16 Decay Chicken 10/10/10 génère 48 Solid Nuclear Waste à la seconde

48 * 10 = 480 mb / s*
*Note qu'afin de traiter 48 items à la seconde il faudrait 24 Chemical Oxidizer
480 / 20 = 24 mb / t
Un roost maxé et 24 Chemical Oxidizer produisent donc seulement 24mb/t
Ils ne sont tout simplement pas assez rapide pour rivaliser avec un setup habituel

Considérons que le joueur possède un setup de fissile fuel est un réacteur capable de générer du 512mb/t une vitesse largement respectable (Ton réacteur tourne à 555mb/t d'à ce que j'ai pu voir sur la rediff):

4 450 000 000 / 512 / 20 = 434 570 secondes
434570 / 3600 = 120,71 heures ~~ 5 jours

Il faudrait donc attendre 120 heures après le lancement de la production de fissile fuel afin d'avoir assez d'Antimatter pour pouvoir craft le poulet tout en skippant le combat du Chaos Guardian (sans prendre en compte la singularité de Reprocessed Fissile Fragment et les 20 d'antimatters requis pour la Creative Energy Cell)

Continuons par l'Unpredictable Dust:

Il en faut donc 89000 ce qui demande:

Krypton:

8 = 500mb donc 16 = 1000mb = 1 unpredictable dust
89000 * 16 = 1 424 000 
Il faut donc 1 424 000 Krypton qui ne peut être fabriqué qu'à partir d'un réacteur à fission ou fusion qui on une vitesse de craft d'un élément par seconde:

1 424 000 / 3600 = 396 heures ~~16.5 jours
Il faudrait donc 396 heures d'attente avec un seul réacteur dédié

Mixtures:

Scraps:

89 000 * 3 = 267 000 scraps
Si on considère le fait qu'il en faut un peu plus de 200k afin d'avoir toutes les scrap singularity afin de finir le pack ça commence à faire très mal à farm sur ce point là mais honnêtement pas impossible

Éléments Alchemistry:

Il y en a 6 différents chacun seulement obtenable avec le réacteur à fusion nous somme donc toujours à une vitesse de craft d'un élément à la seconde:

89 000 * 6 = 534 000
Il faut donc 534 000 éléments

534 000 / 3 600 = 148
Il faudrait donc 148 heures d'attente avec un seul réacteur dédié

Doubt Fluid:

89000 * 3 * 1000 = 267 000 000 mb
Étant donné qu'une Seed of Doubts compactée produit 10mb:
267 000 000 / 10 = 2 670 000
On aurait donc besoin de 2 670 000 de Seed of Doubts mais aussi de 2 670 000 coups de Mechanical Press de Create

Si je ne me trompe pas une Mechanical Press à 512 RPM fait 2 actions par seconde donc si on a disons 10 Press (facilement agrandissable):

2 670 000 / 2 / 10 = 133 500
133 500 / 3 600 = 37 h

Il faudrait donc 37 h afin de produire la quantité nécessaire de Doubt Fluid

### Reasons why this should be added

Enfin bref, le craft est tout simplement trop cher, demandant et long a exécuté afin d'être valable comme option secondaire au fight contre le Chaos Guardian.

Je ne pense pas qu'un craft afin de pouvoir skip un simple boss devrait demander des quantités d'items surpassant celles demandées dans les crafts de l'intégralité des singularités requires (ici avec la singularité de scrap et de reprocessed fissile fragment) et des temps d'attente de plusieurs centaines d'heures.

Je comprend que le but du craft est d'être compliqué et de forcer à l'automatisation mais obliger la construction de mêmes setups et machines des dizaines de fois ne se présentera n'y comme un challenge ou une aide à la progression du joueur mais comme une obligation à passer par le premier choix qui est de combattre le Chaos Guardian

Le craft actuel ne se montre donc pas comme une alternative valable au fight du Chaos Guardian et ne règle donc pas le problème pour lequel il a fondatellement était créé. 

A moins que j'ai raté tout autre alternative à la méthode de craft de celui-ci, dans ce cas là je m'en excuse, je pense que le craft mériterai bien d'un rabaissement de coût.

**Comment by MLDEG** [comment]
Les changements en conséquent seront fait, après mes tests c'est plus jouable de cette façon, il faudra quand attendre un certain temps, mais on peut multiplier les setup pour accélérer le processus.
