### ISSUE TITLE
[Bug]: [Immersive Engineering] Impossible de crafter les Vacumm Tubes

### ISSUE THREAD

**Issue by Crazyweedz** [MLDEG/Ragnamod_VII#56]
### Modpack version

7.1.1

### Description

Il est impossible de crafter les vacuum tubes dans l'Engineer's Workbench. 

Il semblerait qu'il y a un problème avec les tags des wires coppers (voir les images ci-contre)

La recette dans JEI : 
![javaw_G6ErRdEFcs](https://github.com/MLDEG/Ragnamod_VII/assets/9811137/d4e5bc25-6886-4345-b2c0-9e99b59d7f9e)

Le résultat du craft dans mon workbench
![javaw_A14TE010Pr](https://github.com/MLDEG/Ragnamod_VII/assets/9811137/191ef449-80cc-4514-be5d-25b27d504643)

### Steps to reproduce

Pour reproduire le bug, il suffit d'essayer de cratfer les vacuum tubes dans le workbench

### Expected behavior

Le résultat n'est pas celui attendu. Nous devrions avoir les vacuum tubes, or rien ne se passe

**Comment by MLDEG** [comment]
![2024-02-05_20 24 07](https://github.com/MLDEG/Ragnamod_VII/assets/90324978/513ef811-f6f0-414e-8e48-f5744874876a)
Aucun problème de mon coté sur la même version que toi.
