### ISSUE TITLE
[Bug]: Milk Modular Router

### ISSUE THREAD

**Issue by ElKhajiitos** [MLDEG/Ragnamod_VII#57]
### Modpack version

7.1.1

### Description

J'ai l'impression que le Milk n'est pas considéré comme un fluid dans certains cas, comme par exemple l'extraire en fluid depuis une ME interface avec un Modular Router. Il n'y a pas de problème de range ni de config, puisqu'en mettant par exemple un tank à la place de l'interface, ça fonctionne avec exactement la même carte de fluid

![Screenshot_3](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/42774f09-cdda-4442-aba9-f166d980331f)
![Screenshot_4](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/bfa02710-942b-45e5-88c6-f6e48337df8f)
![Screenshot_5](https://github.com/MLDEG/Ragnamod_VII/assets/32446663/32582d30-93da-442f-abf2-21fd124cae62)

### Steps to reproduce

Mettre du Milk dans une ME interface, et tenter de l'extraire via modular router

### Expected behavior

Le Milk devrait être aspiré

### Anything else to note?

ça doit venir de modular router en particulier, puisque l'extraction marche avec laserIO/Pipez mais peut être que tu pourrais le rajouter pour qu'il fonctionne comme les autres

**Comment by MLDEG** [comment]
Je viens de tester avec le même setup que toi et je n'ai aucun problème :/

![Capture d'écran 2024-02-06 010846](https://github.com/MLDEG/Ragnamod_VII/assets/90324978/87864963-fd18-4699-b380-eef2cbc128af)
![Capture d'écran 2024-02-06 010922](https://github.com/MLDEG/Ragnamod_VII/assets/90324978/3c79b044-776d-469d-9911-c3387c1e5199)
![Capture d'écran 2024-02-06 010934](https://github.com/MLDEG/Ragnamod_VII/assets/90324978/ec87f08d-d147-4cfb-8b86-7a1ffee50e34)
