### ISSUE TITLE
[Bug]: Craft Token of Fear qui marche pas

### ISSUE THREAD

**Issue by thedarkonekiller** [MLDEG/Ragnamod_VII#58]
### Modpack version

7.1.1

### Description

Bonjour,
le craft du Token of Fear ne fonctionne pas dans la dernière version du modpack, les autres crafts fonctionnent bien pourtant, j'ai vérifié 20 fois les ingrédients et j'ai cassé le rituel et remis, j'ai redémarré tout mais rien à faire.
J'ai testé en solo ca marche donc c'est un bug server.
J'ai testé sur une nouvelle installation server et pareille ca marche pas :(
Merci d'avance pour votre retour ;)

### Steps to reproduce

Craft du token of fear dans le ritual of the forest ne fonctionne pas

### Expected behavior

voir description

**Comment by MLDEG** [comment]
Je viens de créer un serveur test pour regarder le craft et aucun problème de mon côté.
