### ISSUE TITLE
[Bug]: Le façades de IntegratedDynamics ne fonctionnent plus

### ISSUE THREAD

**Issue by LordDarkWolf** [MLDEG/Ragnamod_VII#59]
### Modpack version

7.1.1

### Description

Bonjour,

Depuis la dernière mise à jour, je ne peux plus faire de façade d'IntegratedDynamics, du moins, je ne peux plus leur appliquer un skin.

![image](https://github.com/MLDEG/Ragnamod_VII/assets/33444937/1da16d2f-6fe5-4cf9-bcef-17e0e4360e95)

J'ai même essayé de supprimer le modpack pour le réinstaller vierge, j'ai le même soucis.

### Steps to reproduce

1. Placer une Façade d'IntegratedDynamics & un block dans une table de craft
2. Aucun résultat n'est proposé

### Expected behavior

Je devrais avoir une façade avec le skin du block

**Comment by MLDEG** [comment]
Alors, le problème vient du mod EnderStorage...
J'explique.

J'ai retiré tous les craft qui pouvait contenir l'ender tank et il se trouve qu'on pouvait faire des façades de ce bloc.
Ce qui a détruit toutes les autres façades lol...

Donc, je vais retirer le craft et probablement changer de mod d'ender storage, sinon si je ne suis pas convaincu, je mettrai une note en tooltips sur l'endertank pour éviter les crashes vu qu'il faut que je retire le craft en question.

Si tu veux un fix rapide, supprime la dernière ligne du fichier craft.js dans server_scripts => e.remove({ input: 'enderstorage:ender_tank' })

**Comment by LordDarkWolf** [comment]
C'est parfait, ça fonctionne, merci.
Et encore merci pour ton travail, je me régales!
