### ISSUE TITLE
[Bug]: Blood Magic / EvilCraft Agonizer placement

### ISSUE THREAD

**Issue by Anloubie42** [MLDEG/Ragnamod_VII#60]
### Modpack version

7.1.1

### Description

With the release 7.1.1 arrived the Digital Agonizer and its counterparts: blood magic agonizer and EvilCraft agonizer.
These blocs have to be placed next to the digital agonizer, but what is not told (and what I had a lot of trouble figuring out), is that the way you place them matters, meaning the EvilCraft one has to be on the right, and the blood magic one has to be on the left

### Steps to reproduce

1. I place the digital mob agonizer
2. I fill it with a blood data model and some generalized prediction
3. I place the BloodMagic agonizer on the right of the digital mob agonizer
4. I place the EvilCraft agonizer on the left of the digital mob agonizer
5. No blood is produced

### Expected behavior

The blood from both mods should be produced not matter

### Anything else to note?

I didn't know exactly if I should categorize this as a bug because it may be a wanted behavior, especially since I found the cause of my problem by clicking on the "require blocks during process" but as this is not written in the questbook I guess it should at least be mentioned

**Comment by MLDEG** [comment]
I mean...
All you had to do was look at the quest screenshot and look at the shape of the blocks to guess for yourself...
At this level, sorry, but I can't do more...
