### ISSUE TITLE
Quêtes fleurs Botania

### ISSUE THREAD

**Issue by WoXayZ** [MLDEG/Ragnamod_VII#62]
### Describe the feature

Il manque la fleur de Mythic Botany nommée Feysythia dans les quêtes

### Reasons why this should be added

Pour que les Generating Flowers soient alignées aux Functional Flowers :p

**Comment by MLDEG** [comment]
Elle ne fonctionne pas cette fleur, sinon elle aurait été mise dans le quest book :)
