### ISSUE TITLE
Tinker Construct Gelot Chicken

### ISSUE THREAD

**Issue by ElKhajiitos** [MLDEG/Ragnamod_VII#63]
### Describe the feature

Ajouter le poulet pour obtenir les Gelot ingot, qui sont demandé pour l'infinity ingot

### Reasons why this should be added

Tous les autres alloy de Tinker demandés pour l'infinity ingot sont disponible en tant que poulet

**Comment by MLDEG** [comment]
Je vais en ajouter plusieurs du coup :)
