### ISSUE TITLE
[Typo]: Quete Turbine Mekanism Structural Glass

### ISSUE THREAD

**Issue by Phaired** [MLDEG/Ragnamod_VII#64]
### Modpack version

7.1.0

### Where is the typo located?

Mekanism quête turbine c'est des structural glass pas des reactor glass
<img width="445" alt="image" src="https://github.com/MLDEG/Ragnamod_VII/assets/65019388/0ca3d912-6734-47b6-82ef-f15e046a8421">

**Comment by Phaired** [comment]
j'ajouterai aussi que la turbine de taille maximal ne semble pas fonctionner sur serveur, après 4h à vérifier

**Comment by Phaired** [comment]
![Serveur](https://github.com/MLDEG/Ragnamod_VII/assets/65019388/7586eaba-c6b3-4787-80cb-14f69d8c30c6)
![Serveur](https://github.com/MLDEG/Ragnamod_VII/assets/65019388/e0b6bad0-2304-4fc0-882d-6bcc1d00e103)
![Serveur](https://github.com/MLDEG/Ragnamod_VII/assets/65019388/80c9b70d-9153-4d05-9f10-20ad19b7b61f)
![Serveur](https://github.com/MLDEG/Ragnamod_VII/assets/65019388/c0e428c1-965f-4e0f-bd30-d38f63967c57)
![Serveur](https://github.com/MLDEG/Ragnamod_VII/assets/65019388/95a53bc4-b87f-4e18-a33e-51f82f542a62)
![Serveur](https://github.com/MLDEG/Ragnamod_VII/assets/65019388/525df417-b75b-4b6f-bbbc-a7c9aa7bf74e)
![Serveur](https://github.com/MLDEG/Ragnamod_VII/assets/65019388/4363b379-013b-4c3c-82dc-0d4dcc58c92e)
![Solo](https://github.com/MLDEG/Ragnamod_VII/assets/65019388/23595dba-f532-49ba-8ead-66508a7563c6)
![Solo](https://github.com/MLDEG/Ragnamod_VII/assets/65019388/f721a72f-9e00-4ecf-a1ea-668e1adecc77)

Voila des screens qui montrent la même turbine qui fonctionne en solo mais pas sur serveur ...

**Comment by MLDEG** [comment]
Le problème de turbine sur server ce sera a Meka qu'il faudra le report car je n'y suis pour rien ;)
et merci pour le typo !

**Comment by Phaired** [comment]
OK merci je report chez eux  :)
