### ISSUE TITLE
[Bug] de certaines plantes dans BotanyPotsTiers

### ISSUE THREAD

**Issue by Mourdida** [MLDEG/Ragnamod_VII#65]
### Modpack version

7.1.1

### Description

Certaines graines reconnues par les Botany Pots de base (@BotanyPots) ne sont pas reconnues par les Botany Pots améliorés (@BotanyPotsTiers). Il s'agit de : 
- Brain Coral Fan (@Minecraft vanilla)
- Dullthorns (@Infernal Expansion)
- Luminous Fungus (@Infernal Expansion)

De plus, les Tube Coral Blocks (@Minecraft vanilla) et Tube Coral Fans (@Minecraft vanilla) rentrent bien dans les Hopper Botany Pots améliorés, mais une fois à maturité, le bloc a un risque de ne rien donner et de rester bloqué à maturité. Un peu comme s'ils attendaient de se faire clic droit, comme dans un Botany Pot amélioré sans hopper. Ce comportement n'est pas observé avec un Botany Pot du mod BotanyPots.

### Steps to reproduce

1. Placer n'importe quel Botany Pot ou Hopper Botany Pot de BotanyPotsTiers et clic droit dessus
2. Essayer de placer un Brain Coral Fan, DullThorns ou Luminous Fungus dans le Botany Pot (d'ailleurs, dans cette fenêtre, ces objets ne sont pas marqués comme "seed item" sous leur nom, contrairement aux autres plantes reconnues)

1. Placer n'importe quel Hopper Botany Pot de BotanyPotsTiers et clic droit dessus
2. Placer un seau d'eau comme soil, et un Tube Coral Block ou Fan comme graine
3. Attendre que la plante ait poussé (parfois 1 seule fois, parfois plusieurs). La plante finira par ne plus pousser, alors qu'il y a de la place dans le pot pour accueillir les produits.

### Expected behavior

Les 3 graines devraient être marquées comme "seed item" et rentrer dans le botany pot de BotanyPotsTiers.

Les 2 coraux devrait continuer à pousser et à donner des produits dans le stockage du Hopper Botany Pot amélioré.

**Comment by MLDEG** [comment]
Ce sera fix pour la prochaine maj, tu peux également le report à Botanypotstiers, car ce sont leurs problèmes que je fix ^^"
