### ISSUE TITLE
[Bug]: Draconium Compound a l'infini dans le combiner

### ISSUE THREAD

**Issue by lulupepe5** [MLDEG/Ragnamod_VII#66]
### Modpack version

7.1.1

### Description

Salut
J'était entrain de faire du Draconium Compound dans le combiner et quand tu fait shift click pour placer les objet directement dans le combiner (faut que tu a tout les objet en grande quantité) et bas sa te fait du Draconium Compound a l'infini .
si tu na pas compris pourrait tu me contacter sur discord pour que je t'envoi la vidéo pour te monter comment j'ai fait merci d'avance 
discord : lulupepe5#1613

### Steps to reproduce

 Quand tu fait shift click pour placer les objet directement dans le combiner (faut que tu a tout les objet en grande quantité) et bas sa te fait du Draconium Compound a l'infini.

### Expected behavior

Que sa en fasse pas a l'infini.

**Comment by MLDEG** [comment]
Bug connu avec Alchemistry, donc il faudra report au mod le problème. (il y a le même bug avec le diamant)

Maintenant à vous de voir si vous voulez tricher pour avancer ou jouer normalement...
