### ISSUE TITLE
[Bug]: Several food items do not have crafting recipes or info in JEI

### ISSUE THREAD

**Issue by g1ngrpr1ncss** [MLDEG/Ragnamod_VII#72]
### Modpack version

7.1.2

### Description

I have been going through all the food items to eat and there are several that do not seem to have a recipe in JEI or even in the book to make them. There may be more but these are the ones I have found so far:

- Beef Jerky
- Pork Jerky
- Tuna Sandwich
- Cheese Cake
- Chunk Nugget

The "Plate/Bowl of [...]" items from Farmer's Delight don't have a tooltip or JEI pop up to show that they are obtained by clicking with a bowl on the main dish, such as placing and then clicking on Shepherd's Pie, to obtain the Plate of Shepherd's Pie.

Additionally the Horizofin Tunid from Blue Skies does not seem to spawn at all, and does not seem to be in the villagers trade pool.

### Steps to reproduce

1. Search for any of the listed items in JEI
2. Click on it for recipe or use
3. Nothing happens

### Expected behavior

1. Search for an item
2. Click on it for recipe
3. Display the recipe
4. Profit ?

### Anything else to note?

Sorry if I just missed something and there is something in game for these. I know food items may be low priority but if I see 750 food items, I'm going to eat all 750 if I can. Thanks for the awesome pack, I haven't had this much fun on modded in awhile.

**Comment by Mourdida** [comment]
Beef and Pork Jerky don't have a recipe in this version of the mod, but maybe MLDEG can add the real recipes ? 
https://www.curseforge.com/minecraft/mc-mods/croptopia/files/4580877

I'm also on a quest to eat all foods. I don't know about Tuna Sandwich, Cheese Cake or Chunk Nugget, but I managed to somehow get Cooked Horizofin Tunid (can't remember how). Raw Horizofin Tunid is nowhere to be found, same as Solnuts...

**Comment by MLDEG** [comment]
Hi!
"I know food items may be low priority" you said, but for me everything in the pack is important!
So to start, thank you for your report on the food :)

Now I've just seen, thanks to your message, the crafts added to version 1.20, I will add them for the next update to the modpack.

Concerning the other crafts, I will make new ones and I will also look for fish that do not spawn.

As for Solnuts, it's a seed that grows in the villages in Everdawn but I will definitely add the seeds to the market.
