### ISSUE TITLE
[Bug]: Oxygen Cans not working correctly if there are 2 cans in inventory or curio slots

### ISSUE THREAD

**Issue by g1ngrpr1ncss** [MLDEG/Ragnamod_VII#74]
### Modpack version

7.1.2

### Description

I'm not sure if this is a mod or modpack issue but I couldn't find anything on the Beyond Earth Github page.
The Oxygen Can from Beyond Earth: Giselle Addon does not behave as expected when 2 are present in inventory only the first one attempts to provide oxygen, even when empty, disregarding the other. This happens both in the main inventory as well as the curio slots.

### Steps to reproduce

1. Craft/Give 2 Oxygen Cans
2. Fill only one of them
3. Go to any beyond earth dimension without atmosphere
4. Put filled oxygen can before the empty one in curio or inventory
5. Can provides oxygen as expected
6. Swap their order
7. Suffocate despite having a full can on you

### Expected behavior

Space Breathing should attempt to pull oxygen from the 2nd can once the first one is empty

**Comment by MLDEG** [comment]
I'm sorry, but I don't understand your issue...
I've been doing my Let's Play in the Earth Space Station for weeks with two oxygen cans, and I've never had a problem, no matter the version of the modpack...

However, check several things.
Whether you have the space suit or the Space Breathing enchantment.
That you right-clicked on the Can to load your armor.

**Comment by g1ngrpr1ncss** [comment]
![2024-02-16_10 35 38](https://github.com/MLDEG/Ragnamod_VII/assets/29153391/4eae276e-6a46-4efd-9875-4b93ecfa848a)
![2024-02-16_10 35 52](https://github.com/MLDEG/Ragnamod_VII/assets/29153391/4ec85e32-87a4-4257-a0c5-bf4e9a65ad59)

I have Space Breathing on my helmet and both cans active on All Armor. I tried crafting 2 new Oxygen Cans just in case there was something weird in item tags and it didn't change anything. I'm not too sure what the problem with the cans are on my end.
