### ISSUE TITLE
[Bug]: missing recipe(Fluid Cell)

### ISSUE THREAD

**Issue by asmussi** [MLDEG/Ragnamod_VII#75]
### Modpack version

7.1.1

### Description

Fluid Cell is not craftable as it is rewarded via quest:"Spray Paint Cans" but the 2 item required to complete the quest are also not craftable since they require a Fluid Cell 

### Steps to reproduce

not something i can recreate, it's there

### Expected behavior

idk what to put here

### Anything else to note?

no

**Comment by MLDEG** [comment]
If you are not using the latest version, make sure to update it before submitting your issue.
