### ISSUE TITLE
[Bug]: nom des items sortant de l'Akashic Tome

### ISSUE THREAD

**Issue by Loudef** [MLDEG/Ragnamod_VII#76]
### Modpack version

7.1.2

### Description

Lorsque l'on enlève un livre de l'Akashic Tome, son nom est modifié en {"translate":"item.<id de l'item>"}

Exemple avec le food book :
![image](https://github.com/MLDEG/Ragnamod_VII/assets/51737892/70540860-70ad-4000-92ae-9f0f1db7f09f)

Reproduction possible avec tout type de livre

### Steps to reproduce

Avant le drop (qui permet de sortir le livre) 
![image](https://github.com/MLDEG/Ragnamod_VII/assets/51737892/89128e51-639c-4cad-bd28-70c3d93131d5)

Je choisi le livre devant sortir :
![image](https://github.com/MLDEG/Ragnamod_VII/assets/51737892/9846cc01-db0c-4290-b004-2faa3441f56c)

Le livre sorti :
![image](https://github.com/MLDEG/Ragnamod_VII/assets/51737892/2d43dd82-36c6-4f1b-9c9e-b2c13e09e1ff)

Si je l'importe de nouveau :
![image](https://github.com/MLDEG/Ragnamod_VII/assets/51737892/f3d6cc52-0063-42fa-adda-2c950332f886)

### Expected behavior

Récupérer le livre voulu sans qu'il soit rename

**Comment by MLDEG** [comment]
C'est un bug de mod, non modpack
