### ISSUE TITLE
Réduire le temps de récupération des items placé avec draconic

### ISSUE THREAD

**Issue by Loudef** [MLDEG/Ragnamod_VII#77]
### Describe the feature

Lorsque l'on place un item avec la fonction "Place item" de draconic evolution (touche P par défaut), il n'est pas possible de le récupérer via shift + click droit. Il faut donc casser l'item poser pour le récupérer mais cela prend plus de 5s et n'est booster par aucun outils.

Comparaison à Ragnamod 6, aucun outil n'etait demandé et l'action de casser demandais le même temps qu'un block de terre miner à la main.

### Reasons why this should be added

Habitude de placer des outils/items utile principalement à une tache à coté de la tache en question.
Exemple : seau à coté de la source d'eau infini en début de jeu

Aussi utiliser pour remplacer les items frames dans certain cas (invisible et permet de poser plusieurs item sur le même block).

**Comment by MLDEG** [comment]
L'option Place item in world est très pratique, mais il ne faut pas shift click droit pour retirer l'item posé, il faut juste click droit :)

**Comment by MLDEG** [comment]
Avant de te répondre j'ai testé de mon coté...
Donc la seule chose que je vois, c'est que tu as un item dans ta off hand, sinon c'est un bug ponctuel qu'il faudra report a Draconic Evolution.

**Comment by MLDEG** [comment]
Alors, je viens de tester du côté SERVER le problème et il y a effectivement un problème coté server pour récupérer les items posé avec Draconic Evolution (mais pas en local)
Donc, il faudra report le problème à Draconic Evolution vis-à-vis de ça.
En attendant, je vais voir si je peux faire quelque chose comme un tag pour le miner à la pioche.
