### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Manoux166** [MLDEG/Ragnamod_VII#78]
### Modpack version

7.1.2

### Description

Impossible de craft le chicken skin

### Steps to reproduce

rechercher la recette du chicken skin sur jei
tenter de craft l'objet via le craft indiqué dans les versions inférieures

### Expected behavior

l'objet est sensé être craft via la cutting board de farmer's delight en utilisant le butcher knive dessus

**Comment by MLDEG** [comment]
Zero problème de mon côté

Et la prochaine fois fait un effort pour le titre sinon je ferme sans vérifier.
