### ISSUE TITLE
[Bug]: Void dimension

### ISSUE THREAD

**Issue by Pacte2047** [MLDEG/Ragnamod_VII#79]
### Modpack version

7.1.2

### Description

Les panneux solaire de FTB industrial contraption ne fonctionne pas dans la void dimension

### Steps to reproduce

Les panneux solaire de FTB industrial contraption ne fonctionne pas dans la void dimension

### Expected behavior

les panneaux devraient fonctionner.

**Comment by MLDEG** [comment]
C'est normal sur le modpack :)
Le void world est par définition une dimension qui n'a ni jour ni nuit et FTB fonctionne différemment que Solar Flux.
