### ISSUE TITLE
[Bug]: Ars Imprégnation doesn't use mana

### ISSUE THREAD

**Issue by VoltalitSama** [MLDEG/Ragnamod_VII#80]
### Modpack version

7.1.2

### Description

Simple multi bloc of ars nouveau, with nothing special.
Our base is in orbit of Mars

### Crashlogs

No crash

### Steps to reproduce

1. Make the multiblock
2. Make it run with essences
3. And no mana is used

### Expected behavior

Mana should be used?
If it is not intended, it is kinda broken!

**Comment by VoltalitSama** [comment]
![image](https://github.com/MLDEG/Ragnamod_VII/assets/133664512/80a900f6-8910-4879-aaab-3e4693657c04)

**Comment by MLDEG** [comment]
It's normal.
