### ISSUE TITLE
[Bug]: Craft manquant pour le BluePrint des Electrode de l'Arc Furnace

### ISSUE THREAD

**Issue by Blackalf14** [MLDEG/Ragnamod_VII#81]
### Modpack version

7.1.2

### Description

Le Blueprint des Electrode de l'Arc Furnace ne possède pas de craft (Il y en avait pourtant bien dans certaines versions antérieures)

### Steps to reproduce

check jei

### Expected behavior

Un craft j'imagine

**Comment by MLDEG** [comment]
Le Blueprint des Electrode de l'Arc Furnace n'a jamais eu de craft :)
