### ISSUE TITLE
[Bug]: Lollipop du mod corail Tombstone 

### ISSUE THREAD

**Issue by BaptisteHardelin** [MLDEG/Ragnamod_VII#85]
### Modpack version

7.1.2

### Description

- Bonjour Ml, je ne sais pas si on peut compter ça comme un bug mais quand on mange le premier Lollipop (reward des quetes d'occultism on en obtient des différentes couleurs), pour le mod spice of life carrot edition c'est comme si on les avaient tous mangés... (du coup pas de gain de coeurs)

### Steps to reproduce

Manger un seul Lollipop de n'importe quel couleur

### Expected behavior

Quand on mange un Lollipop de n'importe quelle couleur  la première fois cela devrait compter pour le mod spice of life carrot edition

**Comment by MLDEG** [comment]
C'est normal, c'est une variante de la lolipop mais en réalité cela reste un seul et même item (quand tu regardes le livre de Spice of Life, tu ne trouveras qu'une seule lolipop :) )

**Comment by BaptisteHardelin** [comment]
Tres bien merci beaucoup !
