### ISSUE TITLE
[Bug]: Enchantement "Gravity Normalizing"

### ISSUE THREAD

**Issue by Artroxs10** [MLDEG/Ragnamod_VII#88]
### Modpack version

7.1.3

### Description

Bonjour,
Lorsque je rends mes Netherite Space Boots unbreakable avec l'Eternal Stella de Forbidden & Arcanus, je ne peux plus appliquer l'enchantement "Gravity Normalizing" de Beyond Earts : Giselle Addon. Et si le je fais dans le sens inverse, mettre l'enchantement puis les rendre unbreakable alors l'enchantement ne fonctionne pas. 

### Steps to reproduce

**Cas 1 :** 
1. Rendre ses Netherite Space Boots unbreakable avec l'Eternal Stella de Forbidden & Arcanus 
2. Essayer d'appliquer l'enchantement "Gravity Normalizing" de Beyond Earts : Giselle Addon sur ses Netherite Space Boots (Unbreakable)

**Cas 2 :** 
1. Appliquer l'enchantement "Gravity Normalizing" de Beyond Earts : Giselle Addon sur ses Netherite Space Boots (vierge)
2. Rendre ses Netherite Space Boots avec l'enchantement "Gravity Normalizing" de Beyond Earts : Giselle Addon unbreakable avec l'Eternal Stella de Forbidden & Arcanus 

### Expected behavior

**Cas 1 :** 
Impossible d'appliquer l'enchantement "Gravity Normalizing" de Beyond Earts : Giselle Addon sur ses Netherite Space Boots unbreakable 

**Cas 2 :** 
Les Netherite Space Boots avec l'enchantement "Gravity Normalizing" de Beyond Earts : Giselle Addon n'ont pas "l'effet"  l'enchantement (Je ne parle pas d'un effet  genre effet de potion). 

### Anything else to note?

C'est un bug que j'avais déjà sur la 7.1.2 

Et déjà merci d'avance !

**Comment by MLDEG** [comment]
l'enchtement Gravity Normalizing utilise de la durabilité pour fonctionner, ou de l'énergie, dans le cas d'une armure incassable il n'y a plus du tout de durabilité donc ça ne fonctionne plus :)
