### ISSUE TITLE
[Bug]: Cable pipez

### ISSUE THREAD

**Issue by Pacte2047** [MLDEG/Ragnamod_VII#91]
### Modpack version

7.1.3

### Description

sur les machine mekanism les câble pipez se déconnecte au redémarrage du serveur (RIP le fission reactor)  

### Steps to reproduce

alimente un multiblock mekanism avec un cable pipez et redémarre le serveur il sera deconnecté 

### Expected behavior

que le câble se déconnecte plus  (Merci de ta compression)

**Comment by MLDEG** [comment]
Une structure meka quand elle est désactivée (donc quand le server est coupé ou que les chunk ne sont plus chargés) n'est plus considéré comme un multiblock et donc n'a plus de sortie d'item ou fluid, et pour le coup Pipez se connecte "seulement" lorsqu'il y a une sortie justement.
Utilise un cable de Meka à la place, cela règlera tous tes problèmes :)
