### ISSUE TITLE
[Bug]: Entangled bloc

### ISSUE THREAD

**Issue by jiaubert** [MLDEG/Ragnamod_VII#93]
### Modpack version

7.1.3

### Description

Il est possible d'entangled un bloc dans toutes les dimensions mais celui-ci ne peut plus être reposé une fois cassé.

Lors du bind, tout va bien : 
![Capture d'écran 2024-02-27 181652](https://github.com/MLDEG/Ragnamod_VII/assets/75979468/70f04624-a0c0-4d5b-99a2-561ec395f690)

Mais une fois que je casse le bloc pour le poser ailleurs : 
![Capture d'écran 2024-02-27 181925](https://github.com/MLDEG/Ragnamod_VII/assets/75979468/c009fa0d-e958-476b-becc-c9bc6b76cfa8)

Les entangled bloc posé avant le passage à la version 7.1.3 fonctionne correctement. 

### Steps to reproduce

1. prendre un entangled bloc et bind une machine / storage controller dessus
2. récupérer l'entangled bloc
3. essayer de le poser dans n'importe quel dimensions et voir le message d'erreur apparaitre

### Expected behavior

l'entangled bloc doit se poser sans afficher de message d'erreur

**Comment by MLDEG** [comment]
Bug du mod depuis sa dernière mise à jour, peut-être que c'est voulu ? il faudra lui demander directement :)
