### ISSUE TITLE
[Bug]: Texture missing from ChemLib ingots during Advanced Hephaestus Forge craft

### ISSUE THREAD

**Issue by g1ngrpr1ncss** [MLDEG/Ragnamod_VII#95]
### Modpack version

7.1.3

### Description

When crafting the Advanced Hephaestus forge, the ingots from ChemLib do not have a proper particle animation.

![2024-02-27_17 34 07](https://github.com/MLDEG/Ragnamod_VII/assets/29153391/2683bc9a-e4e7-4898-8de3-8af5fbbda1da)

### Steps to reproduce

1 - Build Hephaestus Forge multiblock
2- Put required items on pedestals
3 - Launch craft
4 - Texture weirdness

### Expected behavior

Proper texture / particle effect

**Comment by MLDEG** [comment]
Unfortunately, I can't do anything about the textures :(
The ingots are generated directly in the mode code and are monochrome, a color is then applied via a Hexadecimal code, so it does not have the colored texture in its item model.
