### ISSUE TITLE
[Bug]:  interconnexion entre powah / Flux network

### ISSUE THREAD

**Issue by rushdi78** [MLDEG/Ragnamod_VII#98]
### Modpack version

7.1.3 server

### Description

l’énergie n'est pas transmise d'un bloc powah (câble celle, generator) a un flux point or cela fonctionnais avant j'avais rempli une cell de Fux network j'ai pas trouvé de note en parlant sur le bug tracker de flux network ou de powah...

![image](https://github.com/MLDEG/Ragnamod_VII/assets/16599187/67b2cc3c-3243-4c76-9ac0-d71dec4ec4f5)
![image](https://github.com/MLDEG/Ragnamod_VII/assets/16599187/84229a85-a268-4d93-810b-3ec0c5e86625)
![image](https://github.com/MLDEG/Ragnamod_VII/assets/16599187/efcf019f-27bd-4ed3-bb17-5b30587d4083)
![image](https://github.com/MLDEG/Ragnamod_VII/assets/16599187/f5ab5b76-04d8-4ba4-b5ad-b50d668363ae)
![image](https://github.com/MLDEG/Ragnamod_VII/assets/16599187/fb6909dc-8f4e-4e91-ac1a-d4dc0defab4e)

### Steps to reproduce

mettre un flux point sur un bloc powah pouvant transmettre de FE

### Expected behavior

transmistion de FE entre powah et flux point

**Comment by MLDEG** [comment]
Tu utilises un plug et non un point.

**Comment by rushdi78** [comment]
Sans vouloir te vexer regarde mieux les captures ML... D’après le wiki de flux network qu'il faut bien un flux plug pour sortir du courant d'un générateur et l'introduire dans flux network se que j'ai fait et qui marchais jusque la.  Le temps passe, ne jouant que le weekend je me reco et constate mon réseau flux network ne fonctionne plus je ne sais pas si cela est du a la dernière Maj ou pas. J'ai fait des tests pour être sur que c'est pas un bug visuel : recréation du réseau par moi puis par Mme qui joue sur le serveur idem reboot du serveur minecraft et du serveur physique. j'ai check les isues de powa et flux network avant de te soumettre le bug que cela ne fonctionne je ne sais pas d'ou cela peux venir je ne sais pas analyse des log de serveur minecraft. Quelqu'un a il une idée? j’aimerais continuer d'avancer mais sans flux network, câbler toutes les machines vas être compliqué...

**Comment by MLDEG** [comment]
Sans vouloir faire le forcer, le problème bien de ton côté étant donné que Maj apres Maj, je n'ai jamais eu de problème avec Flux Network et ce mod en particulier n'a jamais eu de MAJ durant les différentes mise à jour du modpack.
Donc j'en conclus que le problème est sur ta map, retir ton réseau et refait le, change les plugs et points, je ne sais pas ce que tu pourrais faire étant donné que je suis dans l'incapacité de reproduire le bug vu que ce n'est pas un bug :)
