### ISSUE TITLE
[Bug]: remplir les tests tubes de forbidden and arcanus avec le training dummy

### ISSUE THREAD

**Issue by sphinxnine9** [MLDEG/Ragnamod_VII#99]
### Modpack version

7.1.3

### Description

Si on utilise la Mystical Dagger pour remplir les test tubes sur le training dummy, le tube ce remplit de sang

### Steps to reproduce

1. Avoir la Mystical Dagger
2. Avoir un test tube
3. taper avec la Mystical Dagger le training dummy

### Expected behavior

Selon moi, le test ne devrait pas se remplir, car le dummy n'est pas une entité tuable

**Comment by MLDEG** [comment]
Bug de mod, non modpack.
A report à Forbidden Arcanus.
